### ISSUE TITLE
Specify the case of empty metrics

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#10]
There is unclarity about the handling of empty MetricFamilies. See https://github.com/prometheus/common/issues/50 for discussion.

This issue is about the decision if it should be allowed or not, and then about the documentation of the behavior.

https://github.com/prometheus/docs/issues/544

**Comment by brian-brazil** [comment]
I believe this should be permitted, you can't see metadata without it.

**Comment by mattbostock** [comment]
I don't see any good reason not to allow it.
