### ISSUE TITLE
Termination marker for scrapes

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#11]
https://github.com/prometheus/docs/issues/546

**Comment by brian-brazil** [comment]
I'm for `# END\n` at the end of the format (maybe not the \n if there's an EOF, that's a common mistake).

**Comment by RichiH** [comment]
`# END\n` makes sense. Short IETF speak suggestion: MUST be sent, MUST be accepted without it being sent, SHOULD be exposed to the user.if missing.

**Comment by brian-brazil** [comment]
> MUST be accepted without it being sent,

The whole point of this is to prevent incomplete scrapes, it MUST be rejected if it isn't sent.

**Comment by RichiH** [comment]
Isn't partial information better than no information at all?

I don't feel strongly either way, as things not being `up` (or whatever other implementations call it) is a strong incentive to dig at what's wrong.

**Comment by RichiH** [comment]
Specific to text format (and maybe some others).
