### ISSUE TITLE
Define GOVERNANCE

### ISSUE THREAD

**Issue by caniszczyk** [OpenObservability/OpenMetrics#110]
We expect CNCF projects to define a governance structure. I'd advise you look at some examples:

https://github.com/containernetworking/cni/blob/master/GOVERNANCE.md
https://github.com/envoyproxy/envoy/blob/master/GOVERNANCE.md

The CNI one may be a good fit to cargo cult.

**Comment by RichiH** [comment]
Aye, we already started discussing this in our calls. The plan was to start with the Prometheus one, but I will also have a look at the others.

**Comment by RichiH** [comment]
Plan is to do like-Prometheus-but-with-SABDFL.

**Comment by RichiH** [comment]
Please see https://github.com/OpenObservability/OpenObservability/blob/main/GOVERNANCE.md
