### ISSUE TITLE
Lack of baseline standard spec

### ISSUE THREAD

**Issue by hannibalhuang** [OpenObservability/OpenMetrics#114]
Hi Team,

I've noticed various proto files but it appears there has not been a baseline standard spec that describes the sections those proto should be adhere to. Are we in the process of defining the spec ?

**Comment by RichiH** [comment]
We have the spec hammered out, we are currently in the process of making it
easier to access than by reading tons and tons of documents.

>

**Comment by sandersaares** [comment]
I look forward to seeing a document I could actually try implement.

**Comment by trygve-lie** [comment]
I am also very interested in an actual document one can use to implement. I'm currently in the process of implementing a new metric module and would love to build upon something like this.

Taking the current situation of en existing spec being sorted but no real documentation for implementors being available; what is the best starting point to look at for an implementor?

**Comment by RichiH** [comment]
Please see https://github.com/OpenObservability/OpenMetrics/tree/master/specification on top of the reference implementations in client_python.
