### ISSUE TITLE
Discovery protocol?

### ISSUE THREAD

**Issue by AloisReitbauer** [OpenObservability/OpenMetrics#119]
Are there any plans to also define a discovery protocol for metric endpoints. Ideally, I want to have an easy way to find all the metrics endpoints in a trusted environment. Maybe use something like a UDP broadcast?

**Comment by brian-brazil** [comment]
This is not considered in scope for openmetrics. It's a metrics transfer format, not a monitoring system.

**Comment by madan** [comment]
Makes sense, can we close this issue ?

**Comment by RichiH** [comment]
Yes; closing.
