### ISSUE TITLE
Allow Histogram and Summary use of same base name for same data

### ISSUE THREAD

**Issue by sylr** [OpenObservability/OpenMetrics#120]
https://github.com/prometheus/client_golang/issues/493 moved here at @beorn7 request.

Currently with https://github.com/prometheus/client_golang (I don't know about others client libs) implementation it is not possible to define an `Histogram` and a `Summary` for the same data using the same name cause `_sum` and `_count` for both Histogram and Summary would collide.

Basically in current prometheus exposition format that would look like this:

```
# HELP azure_api_call_duration_seconds_quantile Quantiles of Azure Batch API calls durations in seconds over last 10 minutes or last 50000 observations
# TYPE base_name_quantile summary
azure_api_call_duration_seconds_quantile{...,eq="0.99"} x
azure_api_call_duration_seconds_quantile{...,eq="0.95"} x
...
# HELP azure_api_call_duration_seconds Histograms of Azure Batch API calls durations in seconds
# TYPE azure_api_call_duration_seconds histogram
azure_api_call_duration_seconds_bucket{...,le="0.01"} x
azure_api_call_duration_seconds_bucket{...,le="0.02"} x
azure_api_call_duration_seconds_bucket{...,le="0.03"} x
...
azure_api_call_duration_seconds_bucket{...,le="+Inf"} x
azure_api_call_duration_seconds_sum{...} x
azure_api_call_duration_seconds_count{...} x
```

**Comment by SuperQ** [comment]
Interesting idea, I don't think we'll be able to get this into 1.0, but it's worth talking about.

**Comment by brian-brazil** [comment]
We did actually already discuss this. The outcome was that we didn't want to combine a Histogram and Summary, as we want those using quantiles to use Histograms as they're aggregatable. Summary quantiles are for the many systems out there that only expose data in that form.

**Comment by sylr** [comment]
I'm not a metric expert and have been using Histograms & Quantiles just for a little while now but to me they do not represent the same thing so there is no using one instead of the other.

As far as I see things they do complement each other, quantiles being the base to set up meaningful buckets.

I understand the concern that Quantiles are not aggregatable but what has it to do with being able to name your vectors with a base name and a meaningful suffix ?

If you absolutely want to prohibit Quantiles to be aggregated then you should implement restrictions in the aggregation functions and not forbid an attempt to have a meaningful naming convention.

**Comment by SuperQ** [comment]
They don't represent the same thing, but the point that Brian is making is
that if you have histograms, summary is not useful because the monitoring
system can derive the summary from the histogram data.

>

**Comment by sylr** [comment]
Indeed.

**Comment by jeffwidman** [comment]
Should this be closed?

**Comment by cevian** [comment]
Should it be part of the spec that a histogram and a summary cannot share the same base name? It would simplify implementations to be able to assume this.

**Comment by brian-brazil** [comment]
It'll be part of the spec that they can't share a name.

**Comment by RichiH** [comment]
Please see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#metricset
