### ISSUE TITLE
Should the metric name allow a logic grouping?

### ISSUE THREAD

**Issue by wolfgangB33r** [OpenObservability/OpenMetrics#121]
The metric name syntax definition seems to be flat, meaning no logic grouping is included. 
In Graphite you specify the metric name by using a dot path grouping notation. 
E.g.: host.network.bytes_sent 
Wouldn't it beneficial to also allow such a dot path notation to structure a metric name?

**Comment by SuperQ** [comment]
No, we consider path/hierarchy metric names broken by design. We use labels to create "groupings".

This is a similar philosophy to Metrics 2.0.

We are working on [namespacing](https://github.com/OpenObservability/OpenMetrics/issues/2) to help identify code subsystems.

**Comment by wolfgangB33r** [comment]
After reviewing your reference to the Prometheus metric naming, I come to the conclusion that also a metric name such as http_request_duration_seconds_bucket includes a logic grouping. The prefix of 'http_' obviously means that the metric exists in context of http. 
Isn't that pretty similar to what Graphite does with the dot notation?

**Comment by miton18** [comment]
Agreed with @wolfgangB33r, 

I think that deny dots in metric names is a legacy choice from Prometheus. if you are thinking about building a standard, don't think about the current implementations.

Labels are used to add some context to a metric, this can answer questions like 'how' 'where' 'which' 'who' a metric is collected.

The metric name must be explicit and tell what is observed ('what'): `the numbers of HTTP requests on my webserver` which will produce something like `webserver.api.http.requests.count`

So yes, there is hierarchy to build relevant metric names: 
webserver > api > http > request counter
webserver > api > http > request duration
webserver > database > request counter

**Comment by Dieterbe** [comment]
> This is a similar philosophy to Metrics 2.0.

metrics2.0 attempted  to identify series solely by tags. prometheus and openmetrics use, as far as i can tell, a name/key + tags.

i agree that sometimes in the name/key there is some logical hierarchy as the 2 people above mention.
and there's nothing wrong with that. but i don't think anything really needs to be made explicit here, it's just a natural approach to coming up with metric keys/names.

i will say that it would be great if dots were allowed. that would make it much easier for the graphite world and the prometheus world to converge (e.g. for graphite to adopt openmetrics)

**Comment by RichiH** [comment]
Please see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#metric-naming-and-namespaces
