### ISSUE TITLE
Shoud OpenMetrics be compatible with or consider dropwizard metrics?

### ISSUE THREAD

**Issue by TsingLiang** [OpenObservability/OpenMetrics#122]
Dropwizard metrics format is diffrent from prometheus metrics. And now, dropwizard metrics is widely used in in the field of big data, like Hadoop，Kafka，Spark，JStorm.Shoud OpenMetrics be compatible with or consider dropwizard metrics?

**Comment by brian-brazil** [comment]
As far as I'm aware, there is no Dropwizard metrics format. Dropwizard has been taken into account data model wise.

**Comment by SuperQ** [comment]
From the docs, DropWizard reporting is done via plugins. For example, JMX and json[0], or [prometheus](https://github.com/prometheus/client_java/tree/master/simpleclient_dropwizard).

Supporting OpenMetrics from the DropWizard library should be as simple as updating this plugin.

[0]: https://metrics.dropwizard.io/4.0.0/getting-started.html#reporting-via-http

**Comment by RichiH** [comment]
This will come automatically through https://github.com/prometheus/client_java/tree/master/simpleclient_dropwizard and client_java.
