### ISSUE TITLE
`/metrics` as root level or `/foo/metrics`?

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#123]
IANA will require a well-defined port. In such a setup, having more than one endpoint on a host means reverse proxies. This, in turn, means having several paths on the same port.

If we can reasonably expect to reach this point in common adaption anyway, it might make sense to have something like https://github.com/OpenObservability/OpenMetrics/pull/93/commits/64e25ff2ac9d6a25a86cbd97e32694236dc992f1#diff-38381f1cf184134298e205fddc53d1beR129

```
If more than one metric endpoint needs to be reachable at a common IP address, operators SHOULD consider using a reverse proxy to reach endpoints on localhost addresses and ports.
To ease multiplexing, endpoints SHOULD carry their own name in their path, i.e. `/node_exporter/metrics`.                                                                                                                                                                                              
```

**Comment by brian-brazil** [comment]
I don't see why we should require users to use a reverse proxy for a single port, that's unnecessary complication and considered an anti-pattern in the Prometheus world.

**Comment by RichiH** [comment]
I 100% expect IETF to want us to get a single port. Everything else
comes from that.

**Comment by brian-brazil** [comment]
That may be the case for network devices, but proxies are not something we should be recommending generally.

**Comment by RichiH** [comment]
Assume you have only one port to expose metrics on, what would you do?

**Comment by brian-brazil** [comment]
That'd depend on the architecture of the underlying application. One way or the other, I don't think we should be recommending it.

**Comment by manolama** [comment]
We were chatting here about APIs and a good contract seems to be that you can have anything you want at the root of a path but the start of the API and everything after should always be fixed. Thus if you have defined your API as supporting `/metrics` then `/prom/metrics` or `/cust1/svc1/metrics` are proper but *not* `/metrics/cust`.

**Comment by RichiH** [comment]
Hi @RichiH! ;)

Please see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#overview and https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#iana-considerations-security
