### ISSUE TITLE
Alerting format?

### ISSUE THREAD

**Issue by julianvmodesto** [OpenObservability/OpenMetrics#124]
Where is standardizing alert query and definition format on the roadmap?

**Comment by brian-brazil** [comment]
There's no plans for that, as this is just a transfer format not a query language or full monitoring system.

**Comment by RichiH** [comment]
I can't shake the feeling that there might be overlap with Loki and
other events at some point, but that would be out of scope for
OpenMetrics and touch on OpenObservability.

**Comment by RichiH** [comment]
It's out of scope for OM, but see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#thresholds and CNCF SIG O11y is working on BCP documents.
