### ISSUE TITLE
vector format definition for OpenMetrics ?

### ISSUE THREAD

**Issue by brolga** [OpenObservability/OpenMetrics#127]
My Usecase:
I want to calculate the average direction of a Park of Wind Turbines.
For each turbine i get polar coordinates from the scada system and i convert them to cartesian format to store them into prometheus.

According to the special meaning of histogram i would like to propose to define a type vector for storing the cartesion format:
```
# HELP vector windturbine direction 
# TYPE windturbine_direction_vector vector
wind_turbine_direction_vector{dimension="x"} 0.6 # COS ANGLE
wind_turbine_direction_vector{dimension="y"} 0.2 # SIN ANGLE
```
from multiple vectors i am able to calculate the average of each vector component by grouping it by dimension:

avg(wind_turbine_direction_vector)by(dimension)

to convert the vector back to resulting average angle i use atan2(x,y)
I patched prometheus to be able to use atan2() in alarmrules.

for reference:
https://blog.demofox.org/2013/10/12/converting-to-and-from-polar-spherical-coordinates-made-easy/

It might also be useful to store polar coordinates accordingly:
```
wind_turbine_direction_angle{} 90 
wind_turbine_direction_radius{} 1
```

**Comment by brian-brazil** [comment]
Per previous discussions, this should be done via a gauge rather than adding N different bespoke types.

**Comment by RichiH** [comment]
Related also came up as a use case for Uber, but we decided to not go the InfluxDB route and suggest the use of multiple gauges linked through labels instead.

Also see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#extensions-and-improvements
