### ISSUE TITLE
Support only double values

### ISSUE THREAD

**Issue by bogdandrutu** [OpenObservability/OpenMetrics#132]
The proto data model defines as supported types for Gauge, Counters int and double.

Reasons to not support int:
* The text model supports "All values are float64".
* Converting proto -> text -> proto will may not generate the same proto (no information if the initial value was int or double).
* Int values does not bring too much benefit (float64 has a good enough precision for large ints).
* The metric type does not include information about the exported value type - based on the current proto definition backends need to support for one metric injection of both int/double because this information is not in the MetricDescriptor. This complicates the backend logic for products that want to offer support for both int and double.

I would suggest to simply remove the int support and only support double values.

**Comment by RichiH** [comment]
Please see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#number-types
