### ISSUE TITLE
Unify the end-to-end metrics exposition format for edge computing.

### ISSUE THREAD

**Issue by hellowaywewe** [OpenObservability/OpenMetrics#133]
Hi guys,

I want to initiate the Akraino and the OpenMetrics linkage scheme to unify the end-to-end metrics exposition format for edge computing, which complies with the OpenMetrics standard. 
I have created a wiki page[0], you guys are the experts in OpenMetrics, pls visit it and give me some comments, I'd really like to know what you think, thanks a lot.

[0] https://wiki.akraino.org/display/AK/Akraino+Profiling 

Regards,
Helloway

**Comment by qudongfang** [comment]
I think that end-to-end metrics could be perfectly expressed by open metrics.

```bash
# TYPE http_requests_total counter
http_requests_total{from_service="service1",from_node_id="service1_uuid",to_service="service2",to_node_id="server2_uuid"} 1027 1395066363000
```

**Comment by RichiH** [comment]
Edge computing is covered by OM.

For end-to-end, we suggest putting service spans into exemplars, similar to traces. For detailed logging, a log system might be preferable over a metrics system.
