### ISSUE TITLE
Please don't use Protobuf

### ISSUE THREAD

**Issue by wvxvw** [OpenObservability/OpenMetrics#134]
Protobuf is not an appropriate format for metrics.

Before you dismiss my opinion, here's something to consider: https://github.com/wvxvw/protopy (I'm the author, even though it appears as a fork, I've started the project on an account associated with my former employer).  The project is an implementation of Protobuf format from scratch, in C, as a Python module.  It is far from being perfect C code, but, at the very least, it should tell you that I know how the format works.

Here are my objections:

1. It is not simple enough (you cannot just send a bunch of integers, you must wrap them in `message`).
2. It has too many primitive data-types, which rarely map well to any programming language.
3. It has tons of proprietary extensions you absolutely don't want to deal with.
4. It is not general enough, while it has useless data-structures.
5. It is not possible to stream it (i.e. imagine someone wanting to send time-series, but confuses the message boundary to content boundary, which creates a single huge message with the "infinite" number of the same field repeated over and over, which will never be transferred to the application interested in reading it).
6. It is not possible to generate messages in memory-constrained environment because, despite the "buffer" in the name, there is no plausible implementation that could work with constant memory buffer.  I.e. metrics implemented using Protobuf would necessarily imply a danger of OOM, because they would require dynamic memory allocation.

Unfortunately, trying other popular serialization formats, I'm not aware of a single one that does the job well. So, Thrift would not be a good replacement, neither Ion, AMF, Bencode, BSON...

I'd vote for trying one more time to do this thing from scratch...

**Comment by da77a** [comment]
Re "from scratch" - Describe what you want/need the syntax for metrics to be in ASN.1, pick an encoding to suit use case (streaming? compact? self describing?) - if necessary invent one, or multiple, if appropriate....

**Comment by RichiH** [comment]
Protobuf is not mandatory, but widely adopted so it is supported. Please see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#protocol-negotiation
