### ISSUE TITLE
Consider a structured documentation of labels

### ISSUE THREAD

**Issue by JotBePunkt** [OpenObservability/OpenMetrics#136]
It should be possible to describe the labels structured. That could be a) converted in some documentation or b) be scraped by Prometheus and then provided e.g. in Grafana in the Query editor.

**Comment by RichiH** [comment]
This sounds awfully like half of XML; is there anything beyond what #INFO can do which you want to achieve?

**Comment by JotBePunkt** [comment]
I think XML would not be the right format and it might not be necessary to have it inline in the metrics (meaning you could provide it in a seperate document) But when you have several toolsfrom different teams with several metrics it would be greate if you had a possibility to document the metrics and their tags in a way that could also be handled by Grafana

**Comment by RichiH** [comment]
Please see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#label-namespacing
