### ISSUE TITLE
Specify precisely the semantics of empty label values

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#14]
https://github.com/prometheus/docs/issues/548

**Comment by brian-brazil** [comment]
This is getting a bit into Prometheus-specific semantics, but we should at least specify that an empty label value is the same as that label not existing.

**Comment by RichiH** [comment]
I would argue that this is not implementation-specific, as allowing either will lead to mismatching label sets in different ingestors; thus, it's a wire format consideration.

We do agree that 'empty' means `""` only and _not_ `" "`?

**Comment by brian-brazil** [comment]
Yes, the zero-length label value is empty - not any other value.
