### ISSUE TITLE
support for dots

### ISSUE THREAD

**Issue by Dieterbe** [OpenObservability/OpenMetrics#140]
Correct me if i'm wrong, but i believe OM does not support (allow for) having dots in the name of a metric.
Graphite supports OM in the sense that it can ingest OM data, but the inverse is not true: existing graphite metrics cannot use OM as a format, because OM does not allow for dots and graphite metrics commonly have dots in them.

This seems like a very unfortunate limitation considering OM aims to be a universal standard, and from the graphite project's perspective, we're happy to integrate and adopt as much as we can, but this tiny detail is a major roadblock.

cc @dancech

**Comment by SuperQ** [comment]
This has been discussed at great detail already and it's not likely to happen.

The main reason being that Graphite has logical meaning to those dot trees, and this data model is incompatible with tag-based metrics like OpenMetrics.

Adding dots will add confusion that the metric name contains a hierarchy, which in OpenMetrics it does not. The metric namespace is flat, any dimensions are stored explicitly in labels (tags).

**Comment by Dieterbe** [comment]
note that graphite doesn't use dots solely to imply a hierarchy.
dots are also used to simply separate concepts or words from one another, even in tagged (labeled) metrics.
this page has a few examples of tagged (labeled) metrics that have dots in them:
https://graphite.readthedocs.io/en/latest/tags.html

this example from the prometheus docs
```
http_requests_total{method="post",code="400"}
```
would, in graphite land, be formatted as:
```
http.requests.total;method=post;code=400
```

perhaps the right answer is to not simply allow dots as another approach to what the underscores already do, (though it is unfortunate that prometheus decided to go with a different character for semantically the same thing)
considering the fact that the label specification is also not compatible, and requires a "translation", perhaps we should translate between underscores and dots as well.

**Comment by SuperQ** [comment]
The key word there is "soley". By using it for _both_ word separation and hierarchy it's now ambiguous to which is which. It's now impossible to automatically convert between the two systems and a mapping must be implemented. This is why things like the graphite_exporter and statsd_exporter have configuration files to apply the conversion between the two.

A counter example that makes this more clear is a common use of Graphite before tags:

```
http.requests.total.post.400
```

This is also completely valid Graphite, and commonly used in a lot of code. It's impossible, programatically, to tell where the word separation ends and the tags begin. Also in this use case, the tags have no names, so you need a mapping anyway.

**Comment by beorn7** [comment]
> though it is unfortunate that prometheus decided to go with a different character for semantically the same thing

The decision to not allow dots was deliberate, not a matter of chance or carelessness. Not suggesting a hierarchy was perhaps not even the most important reason. The other one was to reserve the dot for future use as a (real, not just cosmetic) namespacing operator. The latter hasn't happened (yet), but changing things now would probably be at least as tedious as working around the restriction.

**Comment by RichiH** [comment]
Namespacing will be done with `__` to avoid the various issues with dots.

**Comment by Dieterbe** [comment]
I guess we can close this one then. As I pointed out in my last comment, considering that also the label/tag "suffix" needs translating between graphite and openmetrics, we may as well translate between underscores and dots as well (and leave OM itself as is)

Richi if you don't mind, i'ld like to learn a bit more about "the various issues with dots".

**Comment by fitzoh** [comment]
>This has been discussed at great detail already and it's not likely to happen.

Are those discussions documented/available anywhere?

>Richi if you don't mind, i'ld like to learn a bit more about "the various issues with dots".

same

**Comment by RichiH** [comment]
We ended up not doing namespacing through `__`. Dots are not supported by Prometheus so it would be a breaking change from an evolutionary point of view to support them.

Please see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#abnf & https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#metric-naming-and-namespaces
