### ISSUE TITLE
Clarify that counter resets in `_sum` are to be detected in `_count`

### ISSUE THREAD

**Issue by beorn7** [OpenObservability/OpenMetrics#143]
Both summaries and histograms have a `_count` and a `_sum` “field”. They are often both considered counters in every aspects, but both summaries and histograms allow negative observations, which may lead to the `_sum` going down even without a counter reset. Thus, an actual counter reset in the `_sum` series has to be determined by looking at the value for `_count` going down.

Prometheus has never done that, which is a known but mostly ignored bug. (Negative observations are rare in practice, which makes the impact of the bug, once they are happening, even more surprising and hard to spot.) The reason why it is so hard to fix the bug in Prometheus is that Prometheus has no internal notion of the `_count` and the `_sum` of a particular histogram or summary belonging together. It would require either a quite severe layering violation or a new PromQL function (`rate_ratio` or something) or a fundamentally overhauled internal data model to fix the bug.

_However_, this problem of Prometheus shouldn't leak out to all users of OpenMetrics. Thus, I suggest to simply include in the OpenMetrics spec how counter resets in `_sum` are to be detected.

**Comment by beorn7** [comment]
It came to my attention that the plan is now to drop the `..._sum` component from Histograms with negative buckets, avoiding the problem described in this issue. (What's the plan then for Summaries, which do not have buckets?)

I'd very much prefer the approach I have suggested here instead of generally taking away the ability to calculate averages of distributions with negative observations.

There is no excuse why the Prometheus project hasn't documented its deficiency in this regard, so I have now filed https://github.com/prometheus/prometheus/issues/6669 .

**Comment by RichiH** [comment]
We had substantial discussions around this, but in the end, as per https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#histogram and https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#summary this is not permitted for evolutionary reasons.

**Comment by bwplotka** [comment]
This should be now addressed in 2.0 e.g. https://github.com/prometheus/docs/pull/2634
