### ISSUE TITLE
Request to reconsider representation of creation timestamps

### ISSUE THREAD

**Issue by beorn7** [OpenObservability/OpenMetrics#145]
Definitions for the following:
- Metric child: A unique combination of a metric name and label pairs, associated with a sample value and possibly a timestamp and an exemplar.
- Metric family: All metric children of the same name (possibly only one), usually associated with a type, a help string, and possibly a unit.
- Time series: Created from a metric child on the collecting monitoring server by repeated metric collections.

OM allows Counters, Summaries, and Histograms to be associated with a creation timestamp. This is a useful idea, unlocking several interesting use cases.

The decision has been made to represent the creation timestamp in the exposition as a separate line with a different name, built from the name of the associated metric family and a “magic” suffix, in this case `_created`. From what @brian-brazil has told me, I understand that this was an informed decision, which is considered final: “We have already had many long discussions about how to best represent all of these, and it's not something that's going to change at this point.” I don't want to discredit your previous discussions, but a recent discussion in a [prometheus/prometheus issue](https://github.com/prometheus/prometheus/issues/6541) has exposed several problems. I'd like to summarize my concerns here. If that was indeed all considered, or if none of my concerns are serious enough to revisit the decision, feel free to close this issue. (As I already know Brian's point of view, it would be extra convincing if other OM contributors could chime in and support the decision.)

The decision made is similar to how OM represents structured metric types (i.e. the sum and count of Summaries and Histograms and the buckets of a Histogram). While this is in line with an existing approach in the Prometheus text format, I see this approach as problematic in general. I have described my concerns in detail in #144. One aspect here is that I'd prefer to not add more magic suffixes if we can avoid it. The argument of aiming for compatibility with the Prometheus text format only holds for existing magic suffixes, not for newly added ones. In addition, the existing magic suffixes are indeed associated with sample values that create meaningful time series upon collection. The creation timestamp, in contrast, is in general constant over the lifetime of a binary. Without any [changes of the Prometheus server](https://github.com/prometheus/prometheus/issues/6541), the suffixed metric name will create separate (mostly constant) time series for each creation timestamp exposed. As Brian told me, that's even part of the idea: Each line with a sample value in the exposition payload _should_ correspond to a time series on the Prometheus server. While I can see ways of making use of the creation timestamp on the Prometheus side, saving them as an independent time series isn't directly useful. It appears to me both wasteful and semantically wrong. As a counterpoint to the latter, Brian compared the `..._created` timeseries to the likes of `process_start_time_seconds`. Both are time series with a value constant over the lifetime of a binary. I don't think the similarities carry very far here, for the following reasons:
- For `process_start_time_seconds`, there is just no obvious place to associate it with, neither in the exposition format nor in the Prometheus data model. It's fundamentally metadata of the target, but there is no “target” entity in OM or Prometheus. The creation timestamps are, however, associated with their corresponding metric children, an entity we do represent in both OM and Prometheus.
- The cardinality of `process_start_time_seconds` and similar metric families is low, usually one per target. The cardinality of creation timestamps is one per relevant metric child. Or in other words: The cardinality of all counters doubles.
- Even `process_start_time_seconds` is arguably shoehorning target metadata into a time series. But as such it is useful in direct and intuitive ways in PromQL expressions (e.g. to calculate the current uptime or to alert on crashloops). PromQL expressions to utilize the `..._created` time series are way more esoteric. In particular, I see no way how the representation as a time series can solve the problem of [handling counters that spring into existence only with their first increment](https://github.com/prometheus/prometheus/issues/1673). We have to change something more fundamentally in Prometheus anyway. Therefore, we don't have to insist on a representation that allows ingestion without changes in Prometheus.

Fundamentally, the creation timestamp is metadata for a metric child (in contrast to the metadata for a metric family, like type, help, and unit). We already have data in OM that is associated with metric children: explicit timestamps and exemplars. My suggestion would be to treat creation timestamps similar to exemplars, essentially extending the already established syntax for exemplars to additionally or alternatively contain the creation timestamp. It could be in square brackets, or it could be named explicitly:
```
# Option 1: [...]
api_requests_total{status="200"} 4711 # {id="abc} 1 [1578410369.342]
api_requests_total{status="400"} 1971 # [1578410367.123]
# Option 2: named, which reads nicely:
api_requests_total{status="200"} 4711 # {id="abc} 1 created: 1578410369.342
api_requests_total{status="400"} 1971 # created: 1578410367.123
```

**Comment by cevian** [comment]
Where is the `_created` suffix/field documented in this github repo? I am having trouble finding it. If it is somewhere else, where should I look?

**Comment by RichiH** [comment]
There has been extensive discussion around how to represent created metadata, but you do raise valid points. I put this onto the agenda for the next meeting,.

**Comment by RichiH** [comment]
We have have discussed this at length, but decided to leave as-is.

**Comment by camathieu** [comment]
I thing it would be really great to detail -- or give a link to -- the "interesting use cases" that _created metrics are unlocking ?
I'm struggling to find some.

**Comment by bwplotka** [comment]
👋🏽 It would be amazing to revisit this item. Unfortunately, the current approach is not practical to implement for clients (and Prometheus) and blocks the adoption of OM. We started a relevant discussion in the design doc (https://docs.google.com/document/d/1P4SVXBYsDSeUThDJrI_5_aWv6mWemx4x0e0swq7vq6Q/edit#).

We appreciate the amount of work spent on the previous discussions, but 2y later and this is still not adopted. We would love to be able to provide some ideas that perhaps are worth considering.  (: 

Thanks!
