### ISSUE TITLE
How to deal with duplicate labels

### ISSUE THREAD

**Issue by roidelapluie** [OpenObservability/OpenMetrics#146]
`a{b="c",b="d"}`

Please make sure that this case is explicitly documented in OM reference tests and specs.

See https://github.com/prometheus/prometheus/pull/6660

**Comment by brian-brazil** [comment]
It's already specified in the draft, and covered by unittests.

**Comment by roidelapluie** [comment]
> It's already specified in the draft, and covered by unittests.

Thanks, did not find an issue here yet.

**Comment by roidelapluie** [comment]
Does it cover a{b="c",b="c"} ?

**Comment by brian-brazil** [comment]
Yes.

**Comment by RichiH** [comment]
Please see https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#labelset
