### ISSUE TITLE
Current Status of OpenMetrics

### ISSUE THREAD

**Issue by CTJyeh** [OpenObservability/OpenMetrics#147]
The official site for OpenMetrics specifies that the project is coming soon. Looking at the github progress,  the last check in were 4 months ago and there does not seem to be traction since.  
Can someone help clarify on where does the project currently stand at the moment? We are evaluating a few observability standards & apis and we want to make sure we include OpenMetrics in the evaluation if the project is active.

**Comment by brian-brazil** [comment]
We're working on the draft currently. If you're doing application metrics, you should probably use the existing Prometheus client library for your application and OpenMetrics support will come along at some point.

**Comment by CTJyeh** [comment]
At this point,  do you have a target on when the draft will be ready for consumption?  Prometheus removed protocol buffer as an acceptable format.  Does that still hold true for OpenMetrics or is it still under discussion?  I understand that that OM is an evolution out of Prometheus's exposition format; but I am trying to understand how compatible the two will be down the road. Can you hellp clarify to set the right expectations?  (or should we simply go with Prometheus exposition format and can assume the two will be compatible in the future).  Furthermore,  OpenTelemtry has a metrics offering.  Will OM effort be aligned with OT effort ?

**Comment by brian-brazil** [comment]
The formats are similar but slightly different, supporting text is required. If you support Prometheus format, supporting both shouldn't be difficult - just make sure your counters end in _total. Or rely on an existing Prometheus client library to take care of it for you.

**Comment by dannytimothy** [comment]
Can we get an update on the first draft? I run a monitoring org, for now we are just using the Prometheus Exposition Format as Open Metrics, but it can cause some confusion for folks who think we are using Prometheus as a platform.

**Comment by tom-dierckx** [comment]
A follow up on this question how do you guys see relation to the OpenTelemetry spec?

**Comment by bclaise** [comment]
As mentioned during the kubecon session by Brian and Richard, I'm a long time IETF participant and I might be able to help with your IETF draft in OPSAWG.

**Comment by RichiH** [comment]
It's released! https://github.com/OpenObservability/OpenMetrics/blob/master/OpenMetrics.md

I have been in regular contact with the OTel Metrics WG, they committed to supporting OM as a first-class wire format.

@bclaise gladly so; what's your email? I talked with Warren Kumari about this extensively in the past and hope to find fertile ground.

**Comment by RichiH** [comment]
I will close this issue now as it's not needed any more, but feel free to follow up!
