### ISSUE TITLE
Specify whitespace handling in text format

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#15]
https://github.com/prometheus/docs/issues/543

**Comment by brian-brazil** [comment]
The current parser for the Prometheus format is very liberal with whitespace, which makes writing a correct parser quite a bit harder for something that's fairly rarely used.

I think that a small standard is a good standard, so we should choose exactly one representation and make it the representation.

**Comment by RichiH** [comment]
Agreed.

**Comment by beorn7** [comment]
Disagreed.

The additional complexity for parsers is bearable. Generation of the text format is the way more frequent case and should be made easy. Generiation is sometimes directly done by humans, sometimes by "library-less" easy programs/scripts, where remembering the exact whitespace handling is a burden (especially given that the syntactically similar PromQL allows liberal whitespace placement). (Incidentally, @RichiH stated [here](https://github.com/RichiH/OpenMetrics/issues/21#issuecomment-316296840) that whitespace might be easily added by mistake.)

I also don't buy that liberal whitespace is bloating the standard. On the contrary, text-based protocols are more often liberal with whitespace than not, so specifying the contrary might take more energy.

**Comment by brian-brazil** [comment]
> The additional complexity for parsers is bearable. 

I disagree on this point. It took non-trivial extra work on both Prometheus 2.0 and the python client's parser to support it, and neither got it right first time around.

**Comment by RichiH** [comment]
This was discussed extensively during the calls; the final call was to limit whitespace to the minimum. While it's true that human implementation becomes a little harder, the parser runs so much more often, the balance is tipped in its favour.
