### ISSUE TITLE
Specify spelling of non-real numbers

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#16]
How NaN, +inf and -inf are spelled across languages varies. We should specify which are acceptable, probably all variants.

**Comment by brian-brazil** [comment]
This also applies to the histogram +Inf label, we probably want to specify that to be one single value for semantic reasons.

**Comment by RichiH** [comment]
SHOULD be foo, MUST be one of foo, Foo, FoO, etc...

**Comment by manolama** [comment]
This only applies to the text format, no?

**Comment by brian-brazil** [comment]
Yes, this is a text format specification thing.
