### ISSUE TITLE
Decide how much to specify about units

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#17]
There is a Prometheus convention that we use base units like seconds and bytes, rather than a mish-mash of units that are signalled via metadata/metric names.

I think we should formalise this in the spec as a recommended practice.

**Comment by RichiH** [comment]
"SI base units SHOULD be used wherever applicable, except for kg" along with a blurb why everything else can have weird effects like mMb/s in the UI, etc.

Implementation-specific unless we cap the format at float64: We should address anything exceeding 2^53 and requiring negative values so people are aware of this potential tradeoff (even if I can't think of any real-world example, atm).

**Comment by pilhuhn** [comment]
I think units should go into metadata and a standard set of allowed values should be specified. 
The Prometheus convention is helpful, but does not prevent people from supplying arbitrary values.
By specifying an allowed set, it will be possible for clients (e.g. Grafana) to make sense of of the unit and do the correct scaling.

**Comment by brian-brazil** [comment]
I'm against leaving this to metadata, users regularly forget to provide such information leaving you to guess if that latency is seconds or milliseconds. I believe the format should also be usable without any metadata. 

It also results in unnecessary complexity in client library APIs, as users are often asked to choose the unit rather than it being an implementation detail. I think this is largely a relic of metric systems that only support integers, where such a choice on the part of the user was required - but this format is not one of those.

The full best practice in Prometheus is to a) always specify the unit in the metric name and b) you should use seconds. In additional all the timing functions in our client libraries only do seconds, and many exporters convert other units to seconds. This appears to be working out in practice.

**Comment by pilhuhn** [comment]
I doubt that the argument of "forgetting" is better or worse in metadata vs metric name. If the metric name is 'foo', then it is also up for guesswork.

My fear here is rather that people put _s, _sec, _second or _seconds as the unit, which puts the burden on people trying to use the data.

**Comment by brian-brazil** [comment]
It's not a burden if the vast majority of metrics are doing it the same way. This is the convention over configuration approach.

We should specify which of _s, _sec, _second or _seconds to use, as there is a little bit of variation there that should be unified. _seconds is the standard.

**Comment by RichiH** [comment]
Specifying an allowed set works for both metadata and naming; the real concern seems to be to have a limited set of possibilities while covering everything(tm) ever needed.

If we need to specify this anyway, the question becomes how things are best accessible to the user; I would argue that this is better in the case of adopting naming. Grafana et al shouldn't care too much as long as it it well-defined.

Having this information inlined in names avoids having name and metadata disagree about what units are used.

**Comment by sumeer** [comment]
My experience with monarch is that users try to measure a much wider variety of things than I can think of. Using a name suffix is verbose and we can't really provide a convention for each kind of measure.
So we adopted a subset of this standard http://unitsofmeasure.org/ucum.html here https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors and users use metadata to specify the unit (I don't have anything vested in that particular standard, but I would suggest leveraging an existing one rather than taking on this task).

**Comment by RichiH** [comment]
The plan is to refer to other unit standards; referring to SI gives us the widest standardized set of units.

While that link is cloud-specific, e.g. I am certain monarch also ingests Siemens as well, as you can't run water-assisted datacenter cooling in Europe without knowing when your tanks and sumps are likely to facilitate bacteria growth. So, as you imply, we need to refer to the widest set to make sure people who are doing things independently still end up with the same answers.

**Comment by brian-brazil** [comment]
What I really care about is bytes and seconds, as that's where I've seen the most variance in the past. We should probably also specify temperature (which I suspect is going to end up de-facto as Celsius, rather than the SI Kelvin). I think the rest can be handled by allegory, the general idea being metric non-prefixed units - metric as in not imperial.

What I want to avoid is a mix of units being exported, as that's very hard to deal with as the consumer of the metrics. Developers tend to hardcode their own assumptions into the units (e.g. everything is milliseconds), which works fine until they run into code that has different assumptions (e.g. everything is microseconds).

That means I'm against anything that indicates unit prefixes are okay. If you know the prefix, you can do the division/multiplication to remove the prefix.

As a matter of practicality, we will need to specify how to name things with prefixes as it won't always be possible to remove them automatically.

**Comment by RichiH** [comment]
I agree; we need to talk about why one SHOULD NOT use unit prefixes,
but specify how they MUST do it if they think they have a valid
reason.

**Comment by sumeer** [comment]
regarding "you should use seconds. In addition all the timing functions in our client libraries only do seconds, and many exporters convert other units to seconds." mentioned earlier in the thread: there are good reasons why some users do not want floating point values for time or other measures. So I don't see how one can avoid unit prefixes.

**Comment by brian-brazil** [comment]
> there are good reasons why some users do not want floating point values for time or other measures.

Can you list these reasons? In my experience they are due to limitations of systems that only support integers.

**Comment by RichiH** [comment]
Side note: People are free to recast into nanosecond integers or whatever on their end, this about the wire format only.

float64 should have enough precision in any direction with seconds as base unit.

**Comment by sumeer** [comment]
Regarding why folks want something other than seconds, it is the usual reasons: convenience and accuracy (when a system supports both float64 and integers -- I am guessing that prometheus is not encountering this due to not supporting integers). Some examples I have seen:
- User wants to conveniently specify bucket boundaries for a histogram with time duration values that are really small (say always < 1ms). Doing so in microseconds is more convenient.
- Using the same precision as the underlying clock source: for example, if the time being represented was a spanner TrueTime with nanosecond precision, the metric is better represented as an integer with nanosecond units.
- Other things that are better represented as integral time values, like oscillator phase error etc.
- Metric that represents sum of latency values where each latency value is small, so can accurately do sum/count later. Float seconds start losing precision once the sum becomes large, so integer values are preferred.

So once integers are available as a value type, some users will use them to represent things finer grained than a second, so it is preferable if we allow units to be specified as metadata. They can also put it in the metric name suffix when convenient, but that won't cover all use cases (including things like link_speed_bytes_per_sec, which is clunkier than link_speed).

**Comment by brian-brazil** [comment]
> User wants to conveniently specify bucket boundaries for a histogram with time duration values that are really small (say always < 1ms). Doing so in microseconds is more convenient.

Convenient to that single user for that single use case, not everyone else who now has a mix of units.

This is why I'm strongly pushing for seconds, I want what's best for the ecosystem overall not merely for individual isolated use cases.

> Using the same precision as the underlying clock source: for example, if the time being represented was a spanner TrueTime with nanosecond precision, the metric is better represented as an integer with nanosecond units.

What metrics-based use cases do you see for this? Millisecond-level errors are normal for metrics.

> Other things that are better represented as integral time values, like oscillator phase error etc.

The question isn't can it be better represented, the question is if a floating point number is sufficient to represent it.

> Metric that represents sum of latency values where each latency value is small, so can accurately do sum/count later. Float seconds start losing precision once the sum becomes large, so integer values are preferred.

Can you give a concrete example of where users will run into this? We expect this to usually take centuries for any loss of precision, let along a loss of precision that matters in practice.

Also the absolute value of the latency doesn't matter, as we're using floating point.


> So once integers are available as a value type, some users will use them to represent things finer grained than a second, so it is preferable if we allow units to be specified as metadata. 

This is a common misunderstanding, floating point number are perfectly capable of representing things finer grained than a second. It's integers that have the problem in this space.

**Comment by sumeer** [comment]
Those were just examples I already knew of, that were meant to illustrate the larger point I was trying to make that one cannot necessarily say that someone using integer-valued metrics for microsecond values is doing it wrong.

Some options:
A. No support for units metadata and insist that they put the unit in the name suffix. In addition to the seconds discussion, there is also the other example of link_speed_bytes_per_sec which is clunky.

B. Support for units metadata with a limited initial set of units that are supported. Wrt time, this may only include seconds (we can wait till the standard has users that have convincing enough use cases to move beyond seconds). Someone who is not covered may end up putting the units information in the human-readable description metadata for the metric.

C. Fully adopt an existing units standard that gives us a comprehensive set of units metadata (e.g. http://unitsofmeasure.org/ucum.html ) but mention that backends may only support a subset of these.

I am ok with B or C. Other options and thoughts?

**Comment by brian-brazil** [comment]
I'm for A. That doesn't preclude users using microseconds and putting it in the metric name, but it does strongly discourage it.

I think C is impractical, it's too big a standard to tack on.

**Comment by brian-brazil** [comment]
Another thing we could do is rather than specifying float64+uint64, specify decimals and leave it up to the implementation as to how precisely it will handle that (with a minimum requirement of float64).

That sidesteps the units issue, as I think your points come out of precision issues elsewhere.

**Comment by RichiH** [comment]
I think @fabxc had some concerns about arbitrary precision.

**Comment by pilhuhn** [comment]
@brian-brazil Can we / you start a list of base units for various families then? Even if we can't / want to list all of UoM (which I also think is much to big) it may be good to at least have a basic set, that can be documented to make it easier for people.

time: seconds
bytes: bytes
bits: bits
percent: ? -- actually is this then 0-100%  or as people often do 0-1 ?
temperature: celsius? kelvin? 
length: meter

and 2nd for the rates

bits_per_second sounds natural
bits_per_seconds sounds wrong

**Comment by brian-brazil** [comment]
> it may be good to at least have a basic set, that can be documented to make it easier for people.

That sounds like a good idea. There's not too many units in active use in the sort of systems we're talking about.

> bits: bits

Bytes

> percent: ? -- actually is this then 0-100% or as people often do 0-1 ?

Ratios are more base, so 0-1

Note that many existing pieces of software confuse percentages and ratios when it comes to instrumentation, so we'll want to make this one extra clear in the docs.

> temperature: celsius? kelvin?

Defacto it appears to be celsius. I don't think I've seen any other unit in the Prometheus ecosystem.

We'll likely also need volts, amps, joules and something for signal to noise ratios. A more fun one is watts - is that joules per second or does it deserve its own?

> bits_per_second sounds natural

That also sounds better to me, though it'd be bytes_per_second.

**Comment by brian-brazil** [comment]
> I would see bits and bytes as somewhat different here. And yes I know that a Byte has 8 Bits.
> My reasoning goes a long the line, that all the network speeds are given in bits/s e.g. Ethernet has 1 GBit/s or 100MBit/s and not 125MByte/s.

That works until a network engineer meets a non-network engineer, and previous experience with bits vs bytes in the past is a major reason I believe we need to standardise on bytes. You need to be able to compare bytes as measured by the application with bytes as measured by the rackswitch.

**Comment by pilhuhn** [comment]
Hm. I am not really happy, with Bytes <-> Bits but your explanation certainly makes some sense.
Joule by itself is derived from SI units, so watts should also be allowed on their own :)
SNR is a ratio, so unitless.

I started https://github.com/prometheus/docs/pull/803 - not sure if we need to list each and every unit on the world though.

**Comment by brian-brazil** [comment]
I think the common ones and the exceptions are what to worry about. Another fun one is RPM, which per the rules should be per second.

**Comment by RichiH** [comment]
Few notes from the trenches... Not all of these need to be standard in Prometheus and/or OpenMetrics and you can derive some of them from others, but just to show what's in the field

* I do our DC power metering via Prometheus and joule are surprisingly handy; I would not have expected that to be the best way to do this
* relative humidity is critical in datacenters
* air, sometimes water, pressure and pressure differences are critical for maintaining good PUE
* unless you want health authorities to shut down your datacenter, you better keep track of https://en.wikipedia.org/wiki/Siemens_(unit) to track potential bacterial growth
* cos phi is crucial to track load on your UPS - https://en.wikipedia.org/wiki/Power_factor
* liters of diesel / water / oil in storage
* I will soon need g or kg, but I won't disclose why until after PromCon ;)

**Comment by RichiH** [comment]
I forgot dB (relative) and dBa (absolute) for signal-to-noise, dampening, etc in optical networks.

Refraction might be overdoing things, though ;)

**Comment by RichiH** [comment]
Well-defined ones like byte & bit, and RPM should probably be left in their well-defined forms.
