### ISSUE TITLE
Specify how to handle missing time series in metrics

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#18]
We know Summarys will permit missing quantiles.

We should also specify what happens if a Summary is missing _count/_sum or if a Histogram is missing _sum as that can happen with some other monitoring systems. I believe we should not expose them. It should also be made clear that NaN should only be used where it makes mathematical sense, not as a general "missing" signal.

**Comment by manolama** [comment]
By not expose do you mean drop? We should definitely drop incomplete events I'd say :)

**Comment by brian-brazil** [comment]
By not expose I mean exclude that line from the output.

This is an metrics-based standard, there are no events.
