### ISSUE TITLE
Clarify if Summary can have negative values

### ISSUE THREAD

**Issue by bogdandrutu** [OpenObservability/OpenMetrics#187]
I think similarly with [Histogram](https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#histogram)

> Negative threshold buckets MAY be used, but then the Histogram MetricPoint MUST NOT contain a sum value as it would no longer be a counter semantically. Bucket thresholds MUST NOT equal NaN. Count and bucket values MUST be integers.

Probably same clarification can/should be added to [Summary](https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#summary)? Or another option is to add a sentence that explicitly disallows that.

**Comment by brian-brazil** [comment]
It's already covered by "Semantically, Count and Sum values are counters so MUST NOT be NaN or negative." and "Quantile values MUST NOT be negative."

**Comment by bogdandrutu** [comment]
Indeed, but in the context of the whole doc where there is an exception from the rule of "Count and Sum values are counters so MUST NOT be NaN or negative."  it would be easier to understand if a clear statement that says this is not possible was added.

**Comment by brian-brazil** [comment]
I'm not sure what you're getting at, the statements I've quoted make that clear already.

**Comment by bogdandrutu** [comment]
Sounds good

**Comment by beorn7** [comment]
I think the wording in the draft is not strong enough.

It can be easily read in a way that Sum would follow conter semantics if all of the following is true:
- Sum is not NaN.
- Sum is not negative.
- There are no negative bucket thresholds in a Histogram and no negative quantile values in a Summary.

However, you can easily construct situations where all of the above is true but Sum does not follow counter semantics.

It would be much clearer to say something along the lines "Event measurement MUST NOT be negative if Sum is present."

I commented that in the draft before, but the comment got resolved, so I assumed the current wording is deliberate, but I still don't understand how that can be.
