### ISSUE TITLE
Specify Summary quantile semantics

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#19]
Prometheus Summary semantics aren't currently formally specified, however there is by now a defacto standard.

The quantile is over the last 5ish minutes. If there was no data in that time, then a NaN should be reported. This is as a 0 _count would produce NaN when you did `_sum / _count`.

**Comment by brian-brazil** [comment]
As we may be taking in metrics from other systems with different semantics, this will need to be a SHOULD rather than a MUST.

**Comment by RichiH** [comment]
We can suggest a default value, but the wire format arguably needs to be able to handle quantiles over different time frames. Oil pumps are usually queried once per hour or day, power quality meters are precise down to microseconds. I am not even sure if we should mandate the default as SHOULD or MUST.

Prometheus and every other software would be free to drop anything unfitting, of course.

**Comment by brian-brazil** [comment]
The wire format would have no knowledge of the time frame, it's more aiming for some consistency where possible.

**Comment by brian-brazil** [comment]
Another question is should we move the quantile label to the metric name

**Comment by manolama** [comment]
To be super pedantic, should we prevent allowing folks to transport quantiles period? The reason being, at query time, you can't accurately combine them. Instead only transport summaries/histos. (And at the same time, don't allow folks to transport "average")

**Comment by brian-brazil** [comment]
> To be super pedantic, should we prevent allowing folks to transport quantiles period? 

While I agree in theory, in practice these are common enough that I think we have to support them.

Post aggregation in a monitoring system, quantiles and averages are valid gauges to have.
