### ISSUE TITLE
Atomicity of Exemplars to their MetricSet

### ISSUE THREAD

**Issue by mxinden** [OpenObservability/OpenMetrics#192]
Do client libraries have to guarantee atomicity when recording both an event as well as a corresponding Exemplar to a MetricSet?

### Example

Say there is a counter `http_requests_total` which carries both a value - the total count of HTTP requests - as well as the user id of the last request. When business logic records both a new HTTP request as well as the corresponding user id, which of the following metric outputs are valid?

1. Obviously valid case: Recording the HTTP request event as well as its user id in an atomic way, with both being applied before metric collection `http_requests_total 1 # {user_id="KOO5S4vxi0o"} 1`.
2. Questionable: Recording the HTTP request event as well as its user id in a non atomic way, with the counter being increased before metric collection, and the user id being updated after metric collection `http_requests_total 1`.
3. Questionable: Recording the HTTP request event as well as its user id in a non atomic way, with the counter being increased after metric collection, and the user id being updated before metric collection `http_requests_total 0 # {user_id="KOO5S4vxi0o"}`.

### Relevance

This is relevant for the implementation of Exemplars in https://github.com/mxinden/rust-open-metrics-client. More concretely, as one would expect, not having to enforce atomicity in the client library requires less synchronization which would lead to a performance benefit. At the same time, not enforcing atomicity is likely not the expected behaviour on the user side.

**Comment by brian-brazil** [comment]
These are all valid outputs (presuming that the lack of exemplar value in 3 is a typo), however 1 would be preferred. 3 would likely cause confusion relative to 2, so 2 would be better than 3.

**Comment by mxinden** [comment]
Thanks @brian-brazil. I am taking approach (1) in https://github.com/mxinden/rust-open-metrics-client/pull/10.

Do you think it is worth documenting the above as a note for implementors in the specification itself? Along the same lines, I would as well find it helpful to document that observations on histograms should be atomic, e.g. at all times should an observe uphold the requirement that the sum of all buckets equals the `_sum` value. Sorry if I missed this being documented in the spec already.

**Comment by brian-brazil** [comment]
We already document that _count must match the _bucket values, I'm not too worried about races beyond that as they're likely to happen one way or the other.

**Comment by mxinden** [comment]
Closing here then. Thanks for the quick help @brian-brazil!
