### ISSUE TITLE
Histogram buckets in the same MetricFamily

### ISSUE THREAD

**Issue by camathieu** [OpenObservability/OpenMetrics#197]
The spec and client implementations set that all Histograms of the same metric family must have the same buckets

> Similarly all expositions from any consistent binary and environment of an application SHOULD have the same buckets for a given Histogram MetricFamily, so that they can be aggregated by all ingestors without ingestors having to implement histogram merging logic for heterogeneous buckets

However as raised here https://github.com/prometheus/client_java/issues/657#issuecomment-828958978 there are some cases where the monitored latency can be fairly different for two distinct metrics of the family.

```
request_latency_second{target="rapid"} with buckets of [5ms,10ms,25ms,50ms,100ms,200ms,500ms,...]
request_latency_second{target="slow"} with buckets of [1s, 2s, 10s, 30s, 60s, ...]
```

In our case the user of the program can specifies buckets in the configuration of each latency check to override defaults. As some users happen to measure SLAs with those latency checks they need to be able to adjust bucket boundaries accordingly so they can count requests that match their objectives.

The only alternative I see is to move the target name to the metric family name but I already feel like we will end up doing relabeling in Prometheus scrape configuration to get the label back for convenience.

How should we approach such situation with the OpenMetrics datamodel ?
Would you consider relaxing the constraint ?

**Comment by brian-brazil** [comment]
> Would you consider relaxing the constraint ?

The constraint is correct, as already covered in the spec. That constraint is required to be able to aggregate across the MetricFamily, to do otherwise would make the histogram unusable for standard use cases. If you need this then the union of buckets is the best approach.

**Comment by camathieu** [comment]
Ok thanks for the clarifications.
