### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#2]
Do we need namespacing? If yes, what form should it take?

* Schemes
  * Java scheme - works, but long
  * "Play nice" - Won't work
  * Current Prometheus style, i.e. prefix your library name (grpc_, snmp_, etc)
* Possible formats (Java as example)
   * `metric{__namespace__=”io.prometheus.foo.bar...”} 1`
  * `io.prometheus.foo.bar.metric{} 1`

**Comment by brian-brazil** [comment]
There was also a question around namespacing for label names, the general thought was any namespacing from the metric name was sufficient for this when considered against the length increase of the name.

**Comment by RichiH** [comment]
Ceveat: Prometheus (currently) has job labels, so we have an implementation-specific workaround for most name clashes built in. As Sumeer pointed out, this does not cover a wholly generic format, though; especially if we want to 100x its adoption.

**Comment by brian-brazil** [comment]
It's more that Prometheus generally has a way to group similar targets, which is labels for us (the job label being one of those that Prometheus hardcodes).
I imagine that any monitoring system is going to have a similar notion for the same reason.

**Comment by RichiH** [comment]
With clash-free namespacing, I don't think I would still bother with job labels in most if not all of my metrics.

**Comment by brian-brazil** [comment]
You still need job labels (or equivalents), for example it doesn't typically sense to aggregate process_cpu_second_total for different types of binaries.

**Comment by RichiH** [comment]
`io.prometheus.prometheus` would make `process_cpu_second_total` one-to-one and even map across different jobs scraping different prometheus instances for whatever reason.

**Comment by sumeer** [comment]
I agree that metric names are about libraries. My motivation for raising this was primarily to avoid different libraries in the same binary from colliding with each other.

The secondary reason, which is only applicable to strongly typed backends (like monarch, and I don't think applies to prometheus) is that the same metric name cannot have incompatible types (based on some definition of compatibility), and one can significantly reduce such incompatibilities if different libraries don't collide wrt names. There is still the issue that different versions of the same library may have incompatible metric types if the developer is not careful, but that should be less common, especially if the standard provides guidelines on how users should evolve their metric (such guidelines are beneficial even in a backend that doesn't enforce the type at data ingestion time, for queries to work sanely across library versions). For the rare case where the backend does want to ingest both versions which are incompatible with each other, there is always the final option of a backend hack to do a name transformation.

**Comment by brian-brazil** [comment]
I think that no matter what namespacing rules we come up with, incompatible metrics sharing a name is something that a backend will have to deal with in practice. This is already reasonably common from a semantic standpoint in Prometheus (http_request_*), if not necessarily always a collision in the terms you're talking about.

**Comment by RichiH** [comment]
Striking a balance between the two comments above and taking usability into account, I still think having a `__namespace__` or similar makes sense. An ingestor can then decide how to expose this in the UI.

**Comment by brian-brazil** [comment]
`__namespace__` doesn't make sense as a label. If we have a first class notion of namespaces, it needs to go with the metric name.

**Comment by manolama** [comment]
A first class ``namespace`` is very useful for large orgs like ours for routing messages so I'd love to see it as an optional component.

**Comment by brian-brazil** [comment]
What do you mean by routing messages?

**Comment by manolama** [comment]
> What do you mean by routing messages?

So for a centralized monitoring system shared by multiple teams you'll have a common set of collection infrastructure that data is sent to in each data center. At the collection point, the messages can be throttled, dropped or routed based on the property according to quotas, etc. Then messages are sent downstream and based on resourcing, a user may have different storage and processing systems for the metrics based on namespace, e.g. tiny groups go into a shared cluster, bigger groups into dedicated clusters.

Note that this assumes a push or distributed polling mechanism with multiple monitoring servers. But even for a single host solution like Prometheus it's useful as you may want to share resources amongst users, e.g. have a higher retention for team A than team B, whatever.

**Comment by brian-brazil** [comment]
> Then messages are sent downstream and based on resourcing, a user may have different storage and processing systems for the metrics based on namespace, e.g. tiny groups go into a shared cluster, bigger groups into dedicated clusters.

That's what labels are for, not metric names.

Namespaces in this context would be to reduce the impact of two different libraries developed by different people happening to chose the same metric name.

**Comment by manolama** [comment]
> That's what labels are for, not metric names.

Not necessarily as it may be information (meta data) that I *don't* want to record as a label.

**Comment by brian-brazil** [comment]
> Not necessarily as it may be information (meta data) that I don't want to record as a label.

That's a matter for another issue then. Namespaces are not meta data, they would be a component of the metric name.

**Comment by manolama** [comment]
Ok, then I'll pop another issue for that along with meta-data. 

For this case then I would avoid prepending the metric with a namespace. At query time as a user, I want to issue a query like "AVG(temp.celcius) GROUP BY region", not something like "AVG(org.opentemp.temp.celcius + com.mycomp.temp.celcius + temp.celcius) GROUP BY region".

**Comment by brian-brazil** [comment]
That's a matter for the system on the other end, if we choose to go with namespaces.

**Comment by mattbostock** [comment]
I'm not convinced that namespaces are necessary, however if they were implemented I would suggest allowing a single dot in the metric name to specify a namespace, e.g.:

```
namespace.metric_name
a_longer_namespace.metric_name
```

**Comment by brian-brazil** [comment]
If there were implemented, a dot should be avoided given its different meaning in Graphite.

**Comment by mattbostock** [comment]
@brian-brazil: Assuming you're referring to [naming hierarchies](http://graphite.readthedocs.io/en/latest/feeding-carbon.html#step-1-plan-a-naming-hierarchy), what is the problem you're anticipating?

**Comment by brian-brazil** [comment]
Users will use them for label values rather than as namespaces. They're very different ideas, and even the discussion above includes confusion around them.

**Comment by mattbostock** [comment]
@brian-brazil I mostly agree, though is that concern mitigated if only one dot is allowed?

**Comment by brian-brazil** [comment]
Any dots would be an issue I think. I believe all proposals require multiple dots.

**Comment by manolama** [comment]
I'd recommend keeping it entirely separate and letting the user/backend figure out how to combine, be it as a label, a dot, etc.

**Comment by RichiH** [comment]
Dump from the discussion: We might have an optional URL prefix

`http_request_latency`
`om://github.com/RichiH/OpenMetrics/http_request_latency`

**Comment by finkr** [comment]
Allowing multiple exporters to use the same metric name can be seen as a feature (interoperability/compatibility)

For exemple, there are many java exporters which may want to be consistent for usual metrics which come from Java/JMX anyway.

**Comment by brian-brazil** [comment]
I think you're conflating target labels and namespacing.

**Comment by RichiH** [comment]
Update from discussions late last year:

The least bad way we found is `metric_namespace__metric_name`.
