### ISSUE TITLE
Is 42 a valid unit?

### ISSUE THREAD

**Issue by d-frey** [OpenObservability/OpenMetrics#203]
The ABNF grammar for units is:

```abnf
metric-descriptor =/ HASH SP unit SP metricname SP 1*metricname-char LF
```

which means that `42` would be a valid unit. Is this intentional? Or should units be restricted to

```abnf
metric-descriptor =/ HASH SP unit SP metricname SP metricname LF
```

**Comment by brian-brazil** [comment]
As specified it is a valid unit, though that's not something that was ever discussed explicitly.

**Comment by d-frey** [comment]
My 2c: I feel that 42 should be invalid as a unit, but feel free to close this issue if you (and possibly others) feel it should stay as-is.

**Comment by brian-brazil** [comment]
It'd be a breaking change to remove it, and I don't see an issue with is staying as-is. May I ask if this is actually causing you implementation issues?

**Comment by d-frey** [comment]
I am just starting to implement it (switching our old statistics subsystem to use OpenMetrics) and it just seemed super-weird to me that "42" would be considered a valid unit. But I'm only implementing the part that delivers metrics to other systems, not ingesting them.

It also seemed inconsistent to me, as in all other places, metricname is used but in this one place, you can use a metricname that starts with a digit.

There is no technical problem with it from my side, although I don't know about other tools and how they would deal with it. My experience tells me that actually using units like "42" might cause problems with other peoples scripts, etc. as I am quite sure that no one would reasonably expect the unit to start with a digit and have a unit-test (no pun intended) to make sure this works correctly.

**Comment by brian-brazil** [comment]
At its core a unit is a substring of a metric name, and numbers are permitted there as units are never at the start of the name. I've not seen one in the wild, but that doesn't mean that they may not exist. For example maybe you're counting 1040s (USA tax form) per second, though I'm not sure how wise a unit that would be for other reasons.

**Comment by d-frey** [comment]
It's one of those cases that makes sense and makes no sense. In fact, one could argue that I'm counting the 42s per page in the Hitchhiker's Guide to the Galaxy. So yeah, even "42" could be a unit. Still weird.
