### ISSUE TITLE
Hard to read restriction on info metric label names

### ISSUE THREAD

**Issue by ColinH** [OpenObservability/OpenMetrics#208]
I'm having a bit of a hard time with the second sentence of the following part of the description on info metrics:

> A MetricPoint of an Info Metric contains a LabelSet. An Info MetricPoint's LabelSet MUST NOT have a label name which is the same as the name of a label of the LabelSet of its Metric.

How is this not violated by the following example further down the page? It contains the same label names in multiple metric points, is that not exactly what is forbidden above?

```
# TYPE foo info
foo_info{entity="controller",name="pretty name",version="8.2.7"} 1.0
foo_info{entity="replica",name="prettier name",version="8.1.9"} 1.0
```

**Comment by brian-brazil** [comment]
What it's forbidding is both the labelset and the metricpoint containing the same label name, as those would then clash. So for example you can't have two `entity` label names.

The example you show is fine, that's two different metricpoints, each with their own labelset.

**Comment by ColinH** [comment]
Could you please give me an example of something that is forbidden by the rule? Thank you!

**Comment by brian-brazil** [comment]
It's not possible to represent in the text format, it only really can come up in proto.

**Comment by ColinH** [comment]
Ok, I'd like to say "I see", but honestly I don't: Isn't the premise "A MetricPoint of an Info Metric contains a LabelSet" already wrong in proto since in proto only Metrics have Labels, not the individual MetricPoints?

**Comment by brian-brazil** [comment]
> lready wrong in proto since in proto only Metrics have LabelSets, rather than the individual MetricPoints?

InfoValues also have a labels, and if that clashes that's a problem - which is what this is about.

**Comment by ColinH** [comment]
Thanks, now I understand, in the text format there is only one LabelSet for each MetricPoint, in the proto format both the Metric and the MetricPoint have a LabelSet, and that's where the restriction comes into play.

Perhaps the part that I quoted in the original issue should note that it does not apply to the [mandatory] text format but only the [optional] proto format.
