### ISSUE TITLE
Data model vs. protocol specifics

### ISSUE THREAD

**Issue by ColinH** [OpenObservability/OpenMetrics#209]
Given my understanding that MetricPoints and Samples are the same thing two small suggestions.

The following sentence on MetricPoints should probably talk about "multiple Metrics with multiple MetricPoints" instead of "multiple MetricPoints and Samples".

> A correct example where there were multiple MetricPoints and Samples within a MetricFamily would be:

The ABNF grammar uses `sample`, however the document is giving me the idea that "MetricPoint" is the preferred term, wherefore I would suggest using `metric-point` (or `metricpoint`, but see below) in the grammar instead of `sample`.

(On a slightly related note, the ABNF grammar rules could all be written without a hyphen, or all with a hyphen where appropriate, e.g. either `label-name` and `metric-name`, or `labelname` and `metricname`, but not the current `label-name` and `metricname` which, to me, looks a bit random.)

**Comment by brian-brazil** [comment]
> Given my understanding that MetricPoints and Samples are the same thing

They are not the same thing, a MetricPoint translates to one or more Samples in the text format.

**Comment by ColinH** [comment]
So there are five levels? MetricSet, MetricFamily, Metric, MetricPoint, Sample? Then the wording that introduces MetricPoints

> Each MetricPoint consists of a set of values, depending on the MetricFamily type.

should probably be changed to "a set of samples"?

**Comment by brian-brazil** [comment]
Samples only exist in the text format, so aren't mentioned in that part of the doc which is about the overall data model. There is not a 1:1 map between values and samples.

**Comment by ColinH** [comment]
Ok, I can see that the proto format only has four levels, MetricSet, MetricFamily, Metric, MetricPoint.

So in the text format, is the following one Metric with one MetricPoint with three Samples, or one Metric with three MetricPoints with one Sample each?

```
acme_http_router_request_seconds_sum{path="/api/v1",method="GET"} 9036.32
acme_http_router_request_seconds_count{path="/api/v1",method="GET"} 807283.0
acme_http_router_request_seconds_created{path="/api/v1",method="GET"} 1605281325.0
```

Assuming that `9036.32` is what the spec calls a "value", would the optional timestamp, were it to be included in the samples, also be called a "value"?

**Comment by brian-brazil** [comment]
There's insufficient information to tell, but presuming that's a Summary or Histogram it's one Metric with one MetricPoint with three Samples.

**Comment by ColinH** [comment]
Unless the naming convention was violated and `_created` used as part of the name, rather than a format-mandated suffix, shouldn't it be unambiguous, or did I miss something?

And do I understand correctly that multiple MetricPoints are used for one Metric when they differ in the timestamp? Is there any other case?

Thank you!

**Comment by brian-brazil** [comment]
It's ambiguous, presuming that's a fragment it could be 3 unknown or 1 summary/histogram.

> And do I understand correctly that multiple MetricPoints are used for one Metric when they differ in the timestamp? Is there any other case?

Yes. No.

**Comment by ColinH** [comment]
Great, thanks.

**Comment by ColinH** [comment]
> Samples only exist in the text format, so aren't mentioned in that part of the doc which is about the overall data model.

If that is the case then the sentence I stumbled over in #208 should be moved from the data model section to some later section since, on the level of the data model, Metrics have LabelSets, not MetricPoints -- even though the text encoding, by necessity, includes the LabelSet with each MetricPoint in its rendering -- and it is purely an artefact of the proto encoding to allow MetricPoints from different Info Metrics to be encoded in a single Metric object because the LabelSet of the Metrics whose MetricPoints are encoded within a single Metric can be arbitrarily split between that overarching Metric and its MetricPoints.

**Comment by brian-brazil** [comment]
That would be misleading, as someone only reading the proto mightn't see and realise the restriction as it'd be hidden down in the text format despite applying to the data model generally.

**Comment by ColinH** [comment]
On the contrary, the restriction applies neither to the data model (where MetricPoints are a set of values and only Metrics have LabelSets) nor to the text format (where the rendering of each MetricPoint repeats the LabelSet from the Metric it belongs to) so, since it only applies to the proto format, that's exactly where I would expect to find it, in the proto specific section.

**Comment by brian-brazil** [comment]
No, it applies to the data model generally as it'd invalid to have such as thing in the data model independent of any format, and is thus covered in the data model section. In practice it only really comes up for the proto format, but it's still a data model thing.

**Comment by ColinH** [comment]
Sorry, I don't understand. The data model has this, and noly this, to say about MetricPoints:

> Each MetricPoint consists of a set of values, depending on the MetricFamily type.

How can the data model require a restriction on the LabelSet of a MetricPoint when, conceptually, at the level of abstraction of the data model, MetricPoints *do not have* LabelSets?

**Comment by brian-brazil** [comment]
> one can easily argue that this is just a detail of the proto encoding and not actually a data model feature

That however is not what the spec says, and it'd be quite confusing if it did as part of the data model spec would be hidden down in the definition of an optional format.

Is there an actual technical problem you're running into here that we can help you with?

**Comment by ColinH** [comment]
> > one can easily argue that this is just a detail of the proto encoding and not actually a data model feature

> That however is not what the spec says

Ok, but if on the data model level for type INFO both Metrics and MetricPoints have LabelSets then the conclusion is that the text format does not implement the data model because it does not keep this distinction: each sample has a LabelSet with no possibility of deciding which Label belongs to which of the two sets.

I'm trying to implement parts of OpenMetrics and having a bit of a hard time with the choice of the right data structure given this (and some of the other issues).

**Comment by brian-brazil** [comment]
> then the conclusion is that the text format does not implement the data model because it does not keep this distinction: each sample has a LabelSet with no possibility of deciding which Label belongs to which of the two sets.

A format doesn't implement a data model, it marshalls and unmarshalls it. That one case is ambiguous to unmarshall, however it has not been a problem in practice that we're aware of, and all unmarshallings are valid. I'd suggest putting them all in the point.

> I'm trying to implement parts of OpenMetrics and having a bit of a hard time with the choice of the right data structure given this (and some of the other issues).

If you could point to your code so I could have a more concrete idea of what you're up to I'm happy to help, talking about this at an abstract level like this is not likely to be as productive.

**Comment by ColinH** [comment]
It is a really good idea to first define a data model and then do the encodings. However I would find it more beneficial for the data model to be a clean abstract description that is independent of said encodings but as compatible as possible. If that is not what you are going for then we can close this right here.

On one hand I'm just a random guy with some possibly strange opinions on how things should be written. On the other hand I'm a real-world user of this specification, I've been reading it quite carefully, and now I have some feedback on how to possibly improve some parts that might benefit the next readers...

I'll publish the source code if I get it to the point of successfully running the test-suite, that should be the ultimate test of whether I understand everything correctly.
