### ISSUE TITLE
Allow leading/trailing whitespace in label values?

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#21]
It's arguably never a good idea to do this, on the other hand, this can have implications for #14 and possibly others.

To be precise and reproducible, I am somewhat leaning towards "SHOULD not expose leading/trailing whitespace" and "ingestor MUST NOT drop leading/trailing whitespace". But having this strong wording leads to "what about storage/UI/etc which can not properly handle leading/trailing whitespace".

It might be best to prohibit leading/trailing whitespace, along with the implications for #14.

**Comment by RichiH** [comment]
On the other hand, the implementation-specific handling of pretty much any error is to error out completely; that might not be desirable for such a "waek" error, either.

**Comment by brian-brazil** [comment]
I don't see why we'd single out a set of valid UTF-8 values over all the others. Whitespace is significant, is valid to expose, and should be preserved throughout the system.

**Comment by RichiH** [comment]
Whitespace is special inasmuch it's relatively easy to include by mistake and hard for users to realize unless aided by UI & UX throughout the whole generic stack.

**Comment by SuperQ** [comment]
No, label values should be as opaque as possible, I agree with @brian-brazil.  We don't need any exceptions for whitespace in label values.

**Comment by manolama** [comment]
I agree, file this under "Best Practices" :)

**Comment by RichiH** [comment]
Consensus: We allow it and write a warning.
