### ISSUE TITLE
Error in ABNF grammar

### ISSUE THREAD

**Issue by ColinH** [OpenObservability/OpenMetrics#216]
The ABNF grammar states that units can not be empty strings:
```
metric-descriptor =/ HASH SP unit SP metricname SP 1*metricname-char LF
```
However the `empty_metadata` testcase states that this data should be parsed successfully:
```
# HELP a 
# UNIT a 
# EOF
```
(There *is* one space after each `a`.)

Which one is correct?

**Comment by brian-brazil** [comment]
From our discussions, the test is corrects so the spec needs updating.

**Comment by ColinH** [comment]
Then I'll leave this issue open so that it can be closed with the commit that fixes the spec.
