### ISSUE TITLE
Missing unescaped backslashes in ABNF grammar

### ISSUE THREAD

**Issue by ColinH** [OpenObservability/OpenMetrics#217]
The `escaping` testcase says that the escape sequences `\t` and `\z` should be parsed successfully while the ABNF only allows for the escape sequences `\\`, `\n` and `\"`.

**Comment by ColinH** [comment]
Similarly `help_escaping` uses the illegal escape sequence `f`. It also contains an unescaped `"` in a help text, which is again not allowed by the ABNF grammar.

**Comment by ColinH** [comment]
The testcase `label_escaping` also uses the illegal escape sequence `\f`.

**Comment by brian-brazil** [comment]
These are not escape sequences, `\t` for example is interpreted as a backslash followed by a letter t.

**Comment by ColinH** [comment]
But `\t` is forbidden by the ABNF grammar where backslashes may only occur as part of escape sequences.

**Comment by brian-brazil** [comment]
That needs tweaking in the spec then.

**Comment by ColinH** [comment]
The backslash *should* only be allowed as part of a valid escape sequence. Allowing backslashes outside of escape sequences makes the everything more complicated for no good reason, and makes it harder to add new escape sequences in the future.

I say "for no good reason" because on the encoding side it's easier to uniformly escape all backslashes rather than checking for whether the next character can be the second character of an escape sequence and only escaping in that case.

And on the decoding/parsing side allowing spurious backslashes doesn't really simplify anything either. Or am I missing something?

**Comment by brian-brazil** [comment]
There's no need to worry about new escape sequences in future, we've already got all the syntax elements we should ever need.

On the encoding side, you're free to escape everything.
On the decoding side, it's not any more difficult to deal with as you can see from the code.

**Comment by ColinH** [comment]
I'll leave this issue open so that it can be closed with the commit that fixes the spec.
