### ISSUE TITLE
Inconsistent definition of `_created` timestamp for GaugeHistogram

### ISSUE THREAD

**Issue by fstab** [OpenObservability/OpenMetrics#223]
Under [#suffixes](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#suffixes) there's a list of suffixes for metric types:

* Counter: '_total', '_created'
* Summary: '_count', '_sum', '_created', '' (empty)
* Histogram: '_count', '_sum', '_bucket', '_created'
* GaugeHistogram: '_gcount', '_gsum', '_bucket'
* Info: '_info'
* Gauge: '' (empty)
* StateSet: '' (empty)
* Unknown: '' (empty)

This looks like `GaugeHistogram` does not have a `_created` timestamp.

However, if you look at [#gaugehistogram](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#gaugehistogram-1) the `_created` value is explicitly mentioned in the description and shown in the example. So, can `GaugeHistogram` have a `_created` timestamp?

This makes me wonder about `_created` for other types as well. Can you conclude from the OpenMetrics specification that `Gauge`, `StateSet`, `Info`, and `Unknown` must not have a `_created` timestamp, or is there no such restriction?

**Comment by brian-brazil** [comment]
> This looks like GaugeHistogram does not have a _created timestamp.

Correct, only counter-like metrics can have them.

> However, if you look at #gaugehistogram the _created value is explicitly mentioned in the description and shown in the example.

That is a mistake, which should be fixed.

**Comment by brian-brazil** [comment]
Fixed in #226
