### ISSUE TITLE
Missing metrics descriptors in tests

### ISSUE THREAD

**Issue by sinkingpoint** [OpenObservability/OpenMetrics#228]
In the spec, it says:

```
A MetricFamily MUST have a name, HELP, TYPE, and UNIT metadata.
```

but then we have tests like 
 - https://github.com/OpenObservability/OpenMetrics/blob/main/tests/testdata/parsers/counter_exemplars/metrics 
 - https://github.com/OpenObservability/OpenMetrics/blob/main/tests/testdata/parsers/counter_exemplars_empty_brackets/metrics 

that are missing UNIT descriptors and 

- https://github.com/OpenObservability/OpenMetrics/blob/main/tests/testdata/parsers/nan/metrics 
- https://github.com/OpenObservability/OpenMetrics/blob/main/tests/testdata/parsers/no_metadata/metrics

that are missing all metadata. Is this valid, or are the tests wrong? I'm inclined to err on the side that the tests are right and that this statement should be removed from the spec (or at least clarified)

**Comment by brian-brazil** [comment]
That line is in the data model section, how that is rendered is covered in the data formats section. Both the spec and tests are correct.
