### ISSUE TITLE
Tests expect histogram behaviour not outlined in the spec

### ISSUE THREAD

**Issue by sinkingpoint** [OpenObservability/OpenMetrics#229]
# _count can't exist without _sum (and visa versa)

In the [Histogram Section](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#histogram) the spec says:

```
A Histogram MetricPoint MUST contain at least one bucket, and SHOULD contain Sum, and Created values
```

but then we have tests like [bad_histograms_1](https://github.com/OpenObservability/OpenMetrics/blob/main/tests/testdata/parsers/bad_histograms_1/metrics) that have a _sum without a _count (Note that both are "SHOULD contain" not "MUST contain". The Python implementation in this repo says that this errors because a histogram cannot have a _sum without a _count, but this doesn't seem to be formalised anywhere. In addition, that requirement contradicts the statement that:

```
Negative threshold buckets MAY be used, but then the Histogram MetricPoint MUST NOT contain a sum value as it would no longer be a counter semantically
```
i.e. is a _count without a _sum (because we have negative buckets) valid?

# Can't have a negative _sum without negative buckets

Additionally, in the [bad_histograms_7](https://github.com/OpenObservability/OpenMetrics/blob/main/tests/testdata/parsers/bad_histograms_7/metrics) test, we have a negative sum with the python implementation saying that sum cannot be negative without negative buckets but this restriction is not mentioned in https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#gaugehistogram (however that might be implied by the definition of _sum, IMO it should still be called out)

# Histograms can't have negative sums with negative buckets?

Lastly, to me it's kind of confusing that GaugeHistograms _can_ have negative _sums and Histograms can't, even though both can have negative buckets. In the Histograms section, the spec says

```
Semantically, Sum, and buckets values are counters
```

Should that be _Count_ and bucket values are counters?

If you consider a histogram like:

```
# TYPE a histogram
# HELP a A test histogram
a_bucket{le="-3"} 1
a_bucket{le="+Inf"} 1
```

then my one observed value might have been -5, which means my `a_count` would be `1` and my `a_sum` would be -5. This makes sense to me (but maybe I'm misinterpreting), and doesn't violate the semantics of _sum IMO

**Comment by sinkingpoint** [comment]
This got a bit long - I could split it out into separate issues if that would be easier

**Comment by brian-brazil** [comment]
> i.e. is a _count without a _sum (because we have negative buckets) valid?

"If and only if a Sum Value is present in a MetricPoint, then the MetricPoint's +Inf Bucket value MUST also appear in a Sample with a MetricName with the suffix "_count". 

A _count without a _sum is never valid.

> but this restriction is not mentioned in https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#gaugehistogram

Yes it is, "If negative threshold buckets are present, then sum MAY be negative."

> t's kind of confusing that GaugeHistograms can have negative _sums 

GaugeHistograms cannot have negative _sums, as a) GaugeHistograms don't have _sums and b) _sums cannot be negative. They have _gsums, which can be negative if there's negative buckets.

> Should that be Count and bucket values are counters?

No, that'd be incorrect as it'd fail to mention that _sum is a counter.

> This makes sense to me (but maybe I'm misinterpreting), and doesn't violate the semantics of _sum IMO

This does violate the semantics of _sum, as it'd be a) negative b) could go backwards and thereforce c) would not be a counter.

**Comment by sinkingpoint** [comment]
> A _count without a _sum is never valid.

Could you point me to where the spec says this? I might be being dense

>  Yes it is, "If negative threshold buckets are present, then sum MAY be negative.

I suppose my gripe is that the opposite is not specified - there's no "If no negative bucket threshold buckets are present the sum MUST NOT be negative"

**Comment by brian-brazil** [comment]
> Could you point me to where the spec says this? I might be being dense

It's in the above quotation, "**If and only if** a Sum Value is present..."

> I suppose my gripe is that the opposite is not specified - there's no "If no negative bucket threshold buckets are present the sum MUST NOT be negative"

My understanding is that this is the style for writing RFCs.
