### ISSUE TITLE
Add considerations about cardinality?

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#23]
This is implementation-specific, but a few numbers might be useful as a frame of reference.

#22 comes to mind; having arbitrary full even text as label value would be a "metric" in name, but not in practice.

**Comment by brian-brazil** [comment]
Maybe a section around best practices?

I think we'll need to choose a line for where we put things in the spec, and where we just refer off to Prometheus docs. Cardinality, use absolute unixtimes, doing counter math in "Prometheus" and not usually using timestamps are ones we'd want on the spec side I'd say anyway.
