### ISSUE TITLE
Reference parser doesn't obey StateSet rules

### ISSUE THREAD

**Issue by sinkingpoint** [OpenObservability/OpenMetrics#230]
In the spec [it states](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#stateset):

```
A StateSet Metric's LabelSet MUST NOT have a label name which is the same as the name of its MetricFamily.
```

however if we define a test such as:

```
# TYPE a stateset
a{a="test"} 1
# EOF

```

where we _do_ have a labelname `a` which is the same name as the metric family and run the reference parser, we get a succesful parse:

```
python parser.py < ../../testdata/parsers/bad_stateset_info_values_4/metrics 
[Metric(a, , stateset, , [Sample(name='a', labels={'a': 'test'}, value=1, timestamp=None, exemplar=None)])]
```

**Comment by sinkingpoint** [comment]
I note that the parser _does_ implement this restriction for Info types, but for my own OCD could we rephrase

```
An Info MetricPoint's LabelSet MUST NOT have a label name which is the same as the name of a label of the LabelSet of its Metric.
```
to 

```
An Info MetricPoint's LabelSet MUST NOT have a label name which is the same as the name of a label of the LabelSet of its MetricFamily.
````

to be consistent with the stateset version of the same?

**Comment by sinkingpoint** [comment]
In fact, this is actually contradicted by the [simple stateset](https://github.com/OpenObservability/OpenMetrics/blob/main/tests/testdata/parsers/simple_stateset/metrics) test that has a label with the same name as the metric. Is this meant to be:

```A StateSet Metric's LabelSet MUST have a label name which is the same as the name of its MetricFamily.```?

**Comment by brian-brazil** [comment]
That line is in the data model section, and is correct. The reason you can't do that is that we need that label name for the state in the text format, as your example shows.
