### ISSUE TITLE
Specify label ordering

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#25]
Currently there's no specification around ordering of labels for exposition. However in practice client libraries have a consistent ordering due to unittests.

Optimisations in Prometheus 2.0 require a consistent ordering, so we should encourage that to be the case.

**Comment by manolama** [comment]
> Optimisations in Prometheus 2.0 require a consistent ordering, so we should encourage that to be the case.

Encourage definitely but probably not require it.

**Comment by brian-brazil** [comment]
Agreed.

**Comment by mattbostock** [comment]
Ordering alphabetically by label name seems to be the most intuitive.

I'm guessing there's no practical way we can specify stable sorting, so should we consider that an edge case that consumers must handle?
