### ISSUE TITLE
Specify grouping/ordering of timeseries in metrics

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#26]
Currently Prometheus only specifies that histogram buckets must be increasing.

I think we should further specify that a given metric (i.e. same labels) must be together, as that makes things easier for those who support first-class metrics.

**Comment by manolama** [comment]
Are you getting at a compact format for the wire protocols? E.g.

```
{
	"labels": {
		"k1": "v1",
		"k2": "v2"
	},
	"metrics": {
		"m1": 1,
		"m2": 2,
		"m3": 3
	},
	"timestamp": 1483315200.000
}
```
+1 in that case as it saves bytes.

**Comment by brian-brazil** [comment]
This is about grouping and ordering of data, there's no proposals for any form of compression at this stage.

**Comment by manolama** [comment]
Could you clarify? Are you talking about order of values emitted for a time series (e.g. no out-of-order reporting, etc)? And what then do you mean by grouping? Thanks!

**Comment by brian-brazil** [comment]
Say we have a summary metric, which has time series with _count and _sum time series as components. They say we had a label on top of that. We should arrange things so that metadata (if any), metrics  and samples within them are grouped and ordered in a way that makes parsing and processing easier. Having to pull a metric together from time series spread across a response would be annoying.

For example something like:
```
# TYPE s summary
# HELP s some help string
s_sum{l="a"} 0
s_count{l="a"} 2
s_sum{l="b"} 0
s_count{l="b"} 2
```

Rather than:
```
# TYPE s summary
# HELP s some help string
s_sum{l="a"} 0
s_sum{l="b"} 0
s_count{l="b"} 2
s_count{l="a"} 2
```

would be easier to work with for systems with first-class support for compound types.
