### ISSUE TITLE
Reserve a valid character which should not be used by direct instrumentation: `:`

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#28]
The colon is intended for use in a naming convention for aggregation on the Prometheus side, not by instrumentation. That is to say it's reserved for user use.

We should specify this, as it's not uncommon to see instrumentation use this where they should have used an underscore.

**Comment by RichiH** [comment]
This is in between implementation-specific and BCP, and it becomes non-trivial to explain why federating `job:up:count` is valid without falling back to "this is how Prometheus does it". If someone were to cache/proxy using this format "that's one more hop" becomes a non-argument, and an exporter might choose to simply pass things on; without being instrumentation so not covered by your statement.

SHOULD-level of "this is reserved", please use snake_case with this charset unless you must use something else might be an acceptable trade-off.
