### ISSUE TITLE
Decision about protobuf vs. text format

### ISSUE THREAD

**Issue by beorn7** [OpenObservability/OpenMetrics#29]
Do we want to specify both or only one of them? If the latter, should the other be actively discouraged or just excluded from the spec?

@beorn7's essay as a starter for the discussion: https://github.com/RichiH/OpenMetrics/blob/master/protobuf_vs_text.md

**Comment by brian-brazil** [comment]
The current thought is that we'll discuss this spec through the medium of proto, but text will be the transport format.
I've got issues open for what I think should cover all the nitty-gritty to ensure first class metrics are sufficiently specified for use from text, as a lot of things in the current Prometheus ecosystem are implicit in the implementation rather than explicit.

**Comment by manolama** [comment]
I'd like to focus mostly on semantics (the meanings of various components, which bits are required vs optional, etc) and then allow for as many serialization formats as possible, text, proto, thrift, back to JSON, etc.

**Comment by RichiH** [comment]
Consensus: We spec it in Protbuf, but text is the lingua franca

**Comment by rektide** [comment]
#WhyNotBoth? I hope we have some spare capacity some day to explore & see whether protobufs offer any advantage as a transport.

**Comment by beorn7** [comment]
Just adding here that the dissonance of conflating a human-readable and a machine-readable format is increasing with my work on histograms.

It's only the tip of the iceberg that we are now requiring humans to accurately use the right amount of whitespace so that the machines can ingest more easily, or that we have to discuss how exactly floats has to be formatted as strings. With the future high-res histograms, we'll probably end up with base64-encoded strings as values because any human-readable representation of those histograms will be way too verbose for routine machine consumption and over-the-wire transfer.
