### ISSUE TITLE
ENUMs

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#3]
Do we want ENUMs, mapped against the numeric value of the time series?

If yes, we need to make this globally unique to avoid clashes (might be solved by namespacing as per https://github.com/RichiH/OpenMetrics/issues/2)

* `metric_enum{enum=”1:foo,2:bar,3:baz”} 2`
* `metric_enum{enum="foo"} 1, metric_enum{enum="bar"} 0 ….`
  * Have a "# ENUM enum" metadata to hint this to storage
* `metric_enum{enum_1=”foo”,enum_2=”bar”,enum_3=”baz”} 1`

**Comment by brian-brazil** [comment]
I think the 2nd one is the one to go with, as this maintains usable semantics without knowing what an enum is. I'm for keeping things semantically sane for monitoring systems that don't know about an individual optimisation/convention/structure, as that gives forward compatibility as things are extended.

Another point is that a give metric could potentially have multiple enums associated with it, so I'd avoid "enum" as the label but rather something more meaningful.

**Comment by RichiH** [comment]
This might also be a use case for `__enum__` (or whatever name) to mark those as special and not to be touched.

**Comment by RichiH** [comment]
I am somewhat concerned about escaping `,` or whatever in format 1; I am somewhat worried about name clashes for 2, though that might be solved with namespaces.

Personally, I prefer 3, as that is escaped properly, well-contained, and gives me an easy way to see if an ENUM set changed.

**Comment by brian-brazil** [comment]
> Personally, I prefer 3, as that is escaped properly, well-contained, and gives me an easy way to see if an ENUM set changed.

This is semantically very problematic though, as there's an unknown number of arbitrary label names. Any one parsing this would have to special case this to turn it into something useful, which I think we should be avoiding.

**Comment by RichiH** [comment]
@sumeer I have been asked why we want to introduce ENUMs in the first place. IIRC, you had some use data on this. Could you add this in here, please?

**Comment by SuperQ** [comment]
There are a number of "connection state" metrics that are better represented as ENUMs.

For example
MySQL/Galera [wsrep_local_state](http://galeracluster.com/documentation-webpages/galerastatusvariables.html#wsrep-local-state)

Or NTP [peer status](https://www.eecis.udel.edu/~mills/ntp/html/decode.html#peer)
See also: [ntpd_metrics.py](https://github.com/prometheus/node_exporter/blob/master/text_collector_examples/ntpd_metrics.py#L39-L50)

**Comment by sumeer** [comment]
@RichiH there are string use cases in monarch that are really enum, like the current state of something: the process, of a particular connection, of a particular link etc.
But as I had posted on the other thread, monarch does not support enums because we were worried that inconsistencies in the name => value assignment in different binaries, or changes over time, would confuse users who were querying historical timeseries. Strings don't suffer from that issue and it is easy enough to optimize storage in the backend.

**Comment by mattbostock** [comment]
Seems to me that if enums are part of the specification, then most of the value is derived from rejecting samples that don't match the enum. Doing so requires support in libraries that parse the metrics, which will complicate their implementation.

I'm not convinced that enums are valuable enough to warrant the additional complexity, especially considering the issues involved in migrating when the enum schema evolves as @sumeer mentions.

**Comment by RichiH** [comment]
Consensus: Yes, we want ENUMs of some type; moving on to next

**Comment by RichiH** [comment]
Update from last year:

We will be implementing state sets; they resemble ENUMs without hard guarantuess that exactly one value in the set equals `1` while all others equal `0`.
