### ISSUE TITLE
Handle/mark unknown kind of data

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#30]
There was discussion about renaming this, but I forget the conclusion.

**Comment by pimvanpelt** [comment]
Context: Intermediary handlers may not know the type of source data, and they can't therefore set the type on re-exporting. Prometheus has 'untyped' data as a special type for this. There's a lot of existing cases of instrumentation that emits untyped data.

If implementers of OpenMetrics can drop untyped data, this seems fine to me. I do believe ensuring types are set makes reasoning about the data a lot easier between systems (ie avoiding computing rates of guages).

**Comment by RichiH** [comment]
Consensus: There will be `unknown` but it SHOULD NOT be used.
