### ISSUE TITLE
Include base unit names in metric names?

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#31]
https://github.com/prometheus/docs/issues/553

I.e. should we suggest people append `_seconds`, `_bits`, etc as a matter of SHOULD.

**Comment by brian-brazil** [comment]
I think we should include units in metric names, not just restricted to base units. There will be cases where people don't/can't follow the base unit guideline.

This is the same as existing Prometheus guidelines.

**Comment by manolama** [comment]
I'd recommend including units as a separate field. You don't have to have to get into parsing metric names for such information.

**Comment by brian-brazil** [comment]
Metrics should be usable without metadata, which is why they need to go in the metric name.

In addition, technically the entire metric name is the unit. Taking a Prometheus example, the unit of process_cpu_seconds_total is not seconds or CPU seconds, it's CPU seconds of a process. Which are different to CPU seconds of a whole machine.

**Comment by manolama** [comment]
How are we to parse these though, as backends? The order, delimiter, etc get really ugly which is why units are better as a separate field in the message I think. Then let the backend combine it as proper.

**Comment by brian-brazil** [comment]
The current idea would be that you don't. For the main ones like seconds, bytes and celsius parsing is easy, as it'll generally be the last part metric name.
I think the most we can realistically hope for is base units to be strongly encouraged, as any implementation of units beyond that is likely to get into the weeds pretty quickly and largely ignored/used too inconsistently to be useful beyond that.

**Comment by mattbostock** [comment]
> I think we should include units in metric names, not just restricted to base units. There will be cases where people don't/can't follow the base unit guideline.

Should we still recommend that base units be used, where possible? I think doing so has a lot of value as 'best practice'.

**Comment by ericanthonysilva** [comment]
In my experience, having explicit units in metadata causes fewer problems than including them be implicit (or spelled out) in metric names.

**Comment by brian-brazil** [comment]
Prometheus needs the unit to be associated with the metric name, as we discard all metadata. The unit is fundamentally part of the metric name, indeed arguably the entire metric name is the unit.

**Comment by manolama** [comment]
@brian-brazil Prometheus would just append the unit as a suffix. E.g. a library should have a call

`Guage measurement = newGauge("my.metric", "millis", <tags>);`

**Comment by pimvanpelt** [comment]
Consensus -- unit is first class element of data model. Unit will end up in metadata and metric name as a _suffix.

**Comment by RichiH** [comment]
Consensus: unit is SHOULD, and we need a considerations section as to why people should really set it.

**Comment by pimvanpelt** [comment]
Consensus - data model SHOULD include unit and can be 'unknown'; include a consideration section detailing why it's important to set the units.

**Comment by curlup** [comment]
what about inconsistent units - regarding #51
