### ISSUE TITLE
Specify 0..1 vs 0..100 percentages

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#32]
Current BCP is the former as it's easier to calculate with; we should make this explicit in the format.

**Comment by brian-brazil** [comment]
More generally, don't expose ratios at all. Give us the raw data as gauges/counters or a summary/histogram.

**Comment by RichiH** [comment]
Sometimes, those values are pre-aggregated; we should account for this.

**Comment by brian-brazil** [comment]
0..1 is the way, as the ratio is the rawer form.
