### ISSUE TITLE
Start timestamp for points in a cumulative timeseries

### ISSUE THREAD

**Issue by sumeer** [OpenObservability/OpenMetrics#33]
Continuing the discussion from this week's meeting. This is not restricted to COUNTER, since histograms can also be cumulative (which is another discussion -- there is a difference between "type" (int, histogram etc) and "kind" (gauge, cumulative) of a metric).

In this model a cumulative point is a tuple (t_start, t, v) where t is the time when value v was sampled and t_start is when the timeseries had value 0. 
The motivation for the start timestamp is that it is completely describes the cumulative point and does not assume anything about when the last point was collected. This guards against various inaccuracies caused by the monitoring backend losing points or the source being monitored restarting (or clearing its metric state to save memory), and allows for pushing metrics to the monitoring backend.

For example, consider a source generating counter points at timestamp 0min, 10min, 20min, with values 5, 10, 15 and then it crashes, and finally restarts at 57m, and reports a point with value 17 at 60min. We don't want to incorrectly assume that the counter has increased from 15 to 17 over the interval [20m, 60m]. With a perfect failure detector (which of course doesn't exist) a backend could narrow that interval to  [50m, 60m] but it is still less accurate than the real t_start=57min, which is easy for the source to report.

**Comment by brian-brazil** [comment]
I'm against this as I believe it's out of scope. This is a format for transferring metrics which are regularly sampled, and you're proposing here to allow for a form of event logging at an arbitrary timestamp not tied to that sampling.

> The motivation for the start timestamp is that it is completely describes the cumulative point and does not assume anything about when the last point was collected.

This format is intended for metrics, so regular collection is a fundamental assumption of the format.

> allows for pushing metrics to the monitoring backend.

I don't see how this has anything to do with push vs pull, it's the same bits on the wire. Can you expand?

> We don't want to incorrectly assume that the counter has increased from 15 to 17 over the interval [20m, 60m]. 

This is indeed an inaccuracy, however this is rare in practice and I can't recall any Prometheus user ever bringing it up. I don't think we should be violating our status as a metric format for a largely theoretical concern.

**Comment by SuperQ** [comment]
This is not event logging, it simply provides a way to expose the creation timestamp of a new series.  This would solve a number of use cases, for example the problem with counters starting at 1 and functions like `increase()` not having a 0 sample to count that first increment.

> > We don't want to incorrectly assume that the counter has increased from 15 to 17 over the interval [20m, 60m]. 
>
> This is indeed an inaccuracy, however this is rare in practice and I can't recall any Prometheus user ever bringing it up. I don't think we should be violating our status as a metric format for a largely theoretical concern.

While it's somewhat rare in practice that we miss counter resets, this has been discussed before.  This does not violate being a "metric format", it's just a slight variation on buffered samples.

**Comment by brian-brazil** [comment]
> This is not event logging, it simply provides a way to expose the creation timestamp of a new series.

We might be able to crowbar that into a metric, we have process start times as a standard thing after all.

> This does not violate being a "metric format", it's just a slight variation on buffered samples.

Buffered samples would follow the regular sampling, which this is not doing. That's a different use case.

**Comment by RichiH** [comment]
https://docs.google.com/document/d/1PjwV9h1KdhGotm3-kynLAf--BcaBT1ZOIxXclbbyOE8/edit# "HA pair P1/P2 can be spliced together with each other for eventual consistency" is relevant to this discussion.

**Comment by sumeer** [comment]
I don't fully understand the doc, but being able to splice together data from multiple places that have collected it is similar to what monarch does with its replicated collection. Having a start timestamp is part of what allows this to happen: monarch also does push collection where the same point is pushed to all replicas, so merging these different replica timeseries doesn't involve doing any approximations (this was one of the big motivators for doing push) -- I'm guessing that these approximations are what the debate about "changing data" and "sources of truth" on that thread is about.

**Comment by RichiH** [comment]
@sumeer that is a large part of what this is about, but not fully.

Are you able to point us to a more detailed doc on the considerations of merging TS?

**Comment by sumeer** [comment]
there isn't a detailed doc but basically the design is such that each replica should receive some subset of the points of the timeseries generated by the entity being monitored. And each point should be self-contained so that unioning these sets of points can be done independent of considerations of what sampling period (if any -- there are also non-periodic sampling use cases) was being used (since the sampling period is a policy configuration that can change).

**Comment by RichiH** [comment]
Consensus: Start time SHOULD be included where possible. Client implementations MUST offer this.

**Comment by ecki** [comment]
For "external long running" should it be recommended to have the exporter poll async and cache (defends against accidential high frequency polling) or should for more flexibility the scraping trigger the collection. (Possibly with a cache for rate limit). Also in that case should the metrics export the cache timestamp?

**Comment by brian-brazil** [comment]
That's out of scope for openmetrics, and this issue is about something else. Timestamps for general data are to be avoided, as is caching - they cause artifacts and are tricky to deal with.
