### ISSUE TITLE
Add considerations about metric evolution?

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#34]
@sumeer said in https://github.com/RichiH/OpenMetrics/issues/2#issuecomment-316855917

"There is still the issue that different versions of the same library may have incompatible metric types if the developer is not careful, but that should be less common, especially if the standard provides guidelines on how users should evolve their metric (such guidelines are beneficial even in a backend that doesn't enforce the type at data ingestion time, for queries to work sanely across library versions)."

**Comment by brian-brazil** [comment]
I'm not sure what we can do here beyond documenting that basically all changes are breaking (I think changing HELP and appending to an enum are the only things that are okay), and that accordingly you need to be careful.

**Comment by RichiH** [comment]
Seems about right. As it's non-obvious to a large portion of traditional sysadmins, this bears (short) repeating.

**Comment by pauldix** [comment]
Would there be two decisions to be made here?

1. Should we have a version at the top of the metrics format?
2. How should future changes be made? (i.e. should they all be additive like some Protobufs protocols?)

**Comment by brian-brazil** [comment]
This kssje is about individual metrics changing over time, e.g. adding a label. You're looking more for #27

**Comment by pauldix** [comment]
@brian-brazil I was thinking less about meta-data specifically and more about the format (meta and metrics) as a whole. I assume we'll want to version it for library authors to be able to specify what they support.

**Comment by brian-brazil** [comment]
The libraries we're talking about in this issue are the ones using the instrumentation.

**Comment by curlup** [comment]
How about to use an implicit and always assigned version label.
I'm thinking about having some kind of hash out of HELP value put into some `__version` ancillary label. So whenever the meaning of a metric changes and HELP is changed accordingly, it starts to being recorded as a separate, new time serie. 

The backend can give control to the user or make some implicit magic with it.

**Comment by brian-brazil** [comment]
> I'm thinking about having some kind of hash out of HELP value put into some __version ancillary label.

This is not a label semantically, as you can't aggregate it away sanely.

Users will change the meaning of metrics over time, and are unlikely to fully follow any versioning we set (particularly across organisations). Thus the most we can do it point out that it's going to happen, and will break things in almost all cases.
