### ISSUE TITLE
Specify process_* ?

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#35]
https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics is specified for Prometheus client libraries. Do we want to copy this into this spec?

**Comment by RichiH** [comment]
We can try running that as a considerations or BCP section, but I expect it to be removed or forced into it's own ID once we toss this to the IETF.

**Comment by brian-brazil** [comment]
We could also use it as an example of some of the naming/namespacing stuff.

**Comment by RichiH** [comment]
We only have a limited space for "examples" until it gets silly, but yes, I like that approach.

**Comment by pauldix** [comment]
namespacing it is interesting. But would namespacing be used more for specific vendors/implementations of different things? Or I guess namespaces could potentially be hierarchical.
