### ISSUE TITLE
Document that NaN does not mean "missing"

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#39]
This has been a confusion a few times in Prometheus, as we're one of the very few systems that support non-real floating point values. NaN should only be used where it makes mathematical sense.

**Comment by mattbostock** [comment]
@brian-brazil: By 'non-real floating point values', do you mean just NaN? Are there other 'non-real' values we should be explicit about?

Some examples of systems that do support these (and their reasons for doing so, if known) might be useful to the discussion.

**Comment by brian-brazil** [comment]
>  Are there other 'non-real' values we should be explicit about?

Positive and negative infinity are the other two, and Prometheus is one of the very few systems to support those too.

**Comment by manolama** [comment]
I agree, it generally doesn't make sense to be emitting NaNs for "missing" values in a metric. But NaNs a sentinels are useful at query time to show missing values. Is there a better sentinel for that use case?

**Comment by brian-brazil** [comment]
In Prometheus we have no sentinel, the missing data is what indicates it's missing. There's also staleness, which is a Prometheus internal thing.

**Comment by brian-brazil** [comment]
Consensus: clarify this.
