### ISSUE TITLE
New types

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#4]
Add type support for values?

* UNIT64 seems like a given 
* bool can be handled by longer numbers, Prometheus is good at compressing down
  * This is implementation-specific for Prometheus, so we might want to have the type nonetheless
  * bools can be cast as ENUM if people want to see true/false on the UI
* Strings? Will be linked to new issue by Sumeer
* ENUMs: https://github.com/RichiH/OpenMetrics/issues/3

**Comment by brian-brazil** [comment]
For bools we might offer some sort of metadata type hint that the value is a bool, so systems that wish to treat them as something more than float64s can do so.

**Comment by brian-brazil** [comment]
For Uint64, are we okay with the idea that it'd only be for counter time series? This'd make it easier to handle for systems that don't support uint64 if they want to do the modulus thing.

**Comment by RichiH** [comment]
I am not sure on if we are OK with this or not, but I fully expect vendors to ignore this potential part of the spec without second thought.

**Comment by brian-brazil** [comment]
I guess that's something we'll have to figure out when we get to the exact text representation of float64 vs uint64 then. 

Vendors ignoring metadata requirements torpedos many of the ideas we're discussin, so I don't think it's something we should presume if we want to produce something useful.

**Comment by RichiH** [comment]
Generally speaking, yes. But outside of Prometheus, this arguably Prometheus-specific restriction would be perceived as arbitrary and invalid; thus ignored.

**Comment by brian-brazil** [comment]
I note that SNMP has a similar restriction, and I've yet to come across anyone ignoring it (which is unusual for SNMP).

**Comment by RichiH** [comment]
SNMP has stronger typing than we do.

Depending on how we expose float vs uint (dotted vs non-dotted?), especially booleans would be prone to ignoring any such policy by mistake or on purpose.

**Comment by sumeer** [comment]
Regarding string, I looked at monarch usage and there are numerous string valued metrics. I sampled about 100 different ones, and they fall into 3 categories:
- describing what is running: e.g. binary, build labels, cpu architecture, building name, firmware version etc.
  A subcategory is describing the versions of various dynamic configs (that can change in a running process).

- current state of something: the process, of a particular connection, of a particular link. This could be categorized as the enum use-case. Monarch doesn't support enums because we were worried that inconsistencies in the name => value assignment in different binaries would confuse users who were querying historical timeseries.

- last something: e.g. last error message

**Comment by brian-brazil** [comment]
> describing what is running

That's our annotation use case (prometheus_build_info and friends).

> A subcategory is describing the versions of various dynamic configs (that can change in a running process).

I think we can handle that, though it's not quite the same as an annotation from the client library standpoint.

> last something: e.g. last error message

I don't think that's something we can/should really support in a metrics format, as that's got no continuity. That won't stop people, but we can at least discourage it.

**Comment by RichiH** [comment]
> I think we can handle that, though it's not quite the same as an annotation from the client library standpoint.

It's good that @sumeer brought this up. I mulled this over a bit and an `_info` metric would still fit this use case.
Our client library consideration is implementation-specific. Extending those or having a new sub `_info` metric both work. We might want to think about well-defining

* `foo_build_info`
* `foo_runtime_info`
* `foo_config_info`

with the latter two being mostly the same, and probably to be merged. `foo` could be the component or we could have several per sub-component, if applicable.


> I don't think that's something we can/should really support in a metrics format, as that's got no continuity. That won't stop people, but we can at least discourage it.

SHOULD NOT, but if they do it, they MUST follow format X.

**Comment by brian-brazil** [comment]
> SHOULD NOT, but if they do it, they MUST follow format X.

The format will be the same as other strings, the point is more that you SHOULD NOT have regularly changing label values.

**Comment by manolama** [comment]
Strings would be fine with me but we should also allow for extensible types besides the obvious numerics.

E.g. we're pushing histograms, digests and sketches as time series so we'd need to be able to pass a binary payload.

**Comment by brian-brazil** [comment]
I'm against any form of binary payload, to remain forward compatible we should keep to what can be represented as time series for everything.

**Comment by manolama** [comment]
> I'm against any form of binary payload, to remain forward compatible we should keep to what can be represented as time series for everything.

Binary payloads CAN be represented as time series. Histograms are the most obvious use case where you send your histo snapshots as time series and at query time, group by something and pull out the p99. The common work-around is to name metrics ``histo.bkt_0-10``, ``histo.bkt_10-100``, etc. and that's incredibly ugly.

For forwards compatibility we really should have a typed metric.
```
{
	"timestamp": 1501711500.000,
	"tags": {
		"host": "web01"
	},
	"metric": "histo",
	"type": "bucketedHistogram",
	"value": "AgMIGoAAAAADAAAAAAAAAAAAAAAAAPA/AAAAAABARUAAAAAAAADwPwAAAAAAADhAAAAAAABARUA="
}
```

But yeah, if a type isn't specified, let it default to good ole numerics:
```
{
	"timestamp": 1501711500.000,
	"tags": {
		"host": "web01"
	},
	"metric": "system.cpu.busy.pct",
	"value": 42.5
}
```

**Comment by brian-brazil** [comment]
> Binary payloads CAN be represented as time series.

Not as numeric time series.

Every new non-numeric type is a type that every system on the other end must support, however that's not an issue for time series which are all counters and gauges - you'll get something meaningful even if you don't have first class support for a particular type.

**Comment by manolama** [comment]
> Every new non-numeric type is a type that every system on the other end must support, however that's not an issue for time series which are all counters and gauges - you'll get something meaningful even if you don't have first class support for a particular type.

Not if the standard is extensible and typed. Users can choose to implement types their pipline supports.

**Comment by brian-brazil** [comment]
A goal of this standard is that it's not tied to particular monitoring systems. If a new type isn't at least somewhat meaningful to all consuming systems, then that works against the goal of being a standard.
