### ISSUE TITLE
Add considerations on label size?

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#48]
Consensus: We want to put in some sanity considerations.

**Comment by pimvanpelt** [comment]
What are label lengths currently capped at in implementations (Prometheus, StackDriver, InfluxDB)?
Is there a common length we should strive for? If we want sanity considerations, this should be a MUST in OpenMetrics, lest instrumentation libraries cause issues in backends and frontend rendering etc.

**Comment by robskillington** [comment]
A limit of some kind honestly would be nice to make sure an implementation is compliant or not (since some will implement a limit themselves, and therefore not really compliant if the spec does not specify a limit).
