### ISSUE TITLE
Should unit be a separate field in the datamodel?

### ISSUE THREAD

**Issue by tomwilkie** [OpenObservability/OpenMetrics#49]
...and potentially appended to the metric name in the text format?

Alternatively should it just be part of the metric name?

**Comment by manolama** [comment]
I'd like to see it separate then implementations can concatenate it however they see fit. I think it's a bad idea to rely on parsing information out of a metric name based on underscores, dots or anything like that.

**Comment by pimvanpelt** [comment]
in #31 we converged on unit being a first class citizen in the datamodel.
I agree with Chris that parsing information out of metric names (as prometheus does today) should be avoided in OpenMetrics.
