### ISSUE TITLE
Timestamps subseconds

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#5]
This is already already decided, this issue merely documents the TODO.

**Comment by brian-brazil** [comment]
To be exact, timestamps will be represented as unixtime seconds and allow subsecond precision. How much precision is open, but at least ns is required.

**Comment by manolama** [comment]
What's the format? ``<seconds>.<subseconds>``?

**Comment by brian-brazil** [comment]
That's something to be decided at a later stage, but I imagine it'll look something like that.

**Comment by bogdandrutu** [comment]
My 2 cents here:
The new timestamp definition in most of the languages is uint64 seconds + uint32 nanoseconds (java Instant). In proto we can use the proto3 Timestamp definition.

**Comment by manolama** [comment]
What about all the happy fun rounding errors, accuracy problems, etc with floating point? If we're expecting this spec to be a standard with accuracy and precision shouldn't we maintain timestamps as integers (when using Unix Epoch) or strings (ISO) 8601?

**Comment by bogdandrutu** [comment]
> What about all the happy fun rounding errors, accuracy problems, etc with floating point?
We will miss them 🥇 

I still think the java Instant format is better:
https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html

Also Google uses this format internally:
https://github.com/abseil/abseil-cpp/blob/master/absl/time/time.h

I need to check what other languages are proposing but for a standard this makes the most sense to me.

**Comment by SuperQ** [comment]
According to my math, we have until 2255 before we exhaust 2^53 bits of precision of float64 microseconds.

**Comment by manolama** [comment]
@SuperQ It's not just about the exhaustion, it's about representation and arithmetic. I still love this guy's site: http://floating-point-gui.de/

**Comment by SuperQ** [comment]
It is just about representation, as this is all we are concerned about here.  Metrics systems are allowed to store the data as they see fit.  For example, in Prometheus we throw away anything past milliseconds.

**Comment by manolama** [comment]
Representation as in IEEE 754 can't represent nanosecond precision in the fractional component. It's fine for millis but you can't go beyond. As an example just using micros:
```
double ts = 1483315200.000000000;
    int range = 1000 - 1;
    for (int i = 0; i < range; i++) {
      System.out.println(String.format("%.6f", ts));
      ts = ts + 0.000001D;
    }
```
the final values are:
```
1483315200.000948
1483315200.000949
1483315200.000950
1483315200.000951
1483315200.000952
```
instead of `1483315200.000999`. We _could_ represent the timestamps as strings and have producers combine on the dot or consumers split on the dot and process two ints. BUT you can't just encode over the wire as a float64 and get the proper value back out.

**Comment by RichiH** [comment]
Consensus: We want subsecond precision; implementations CAN support this, they MUST support seconds. Paul needs nanoseconds.

**Comment by ecki** [comment]
What about the actual time base, if you go to nanosecond precision the question is if you want to deal with leap seconds or go to a clock like TAI based reference? (I think even with high precision clocks like PTP (with the exception of GPS) it seems however uncommon...

In any case defining a <seconds>.<fraction> string representation (text format) seems to be most compatible and general. It can be mapped to doubles as well as to uint64:uint32 tuples. The later would be most likely best for typed binary formats.

**Comment by brian-brazil** [comment]
The plan is to stick with unixtime, as that's what everyone is likely using anyway.
