### ISSUE TITLE
Specify inconsistent labels

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#51]
Within a given metric, different children might have different labels. While this is wrong for direct instrumentation, it can be valid once target labels are involved. Thus this must be allowed for in the format, but some words of warning would be good.

**Comment by curlup** [comment]
> words of warning

never work IMHO

**Comment by curlup** [comment]
@hbs we overcome this by allowing `not` with wildcard selector. So suppose we have 2 metrics
```
metric{label="value"}
metric{label="value", additional="label"}
```
then one can select only subset by `metric{label="value" AND NOT additional~"*"}`

**Comment by hbs** [comment]
This is kind of disturbing, as you must know which extra labels might have been added in other series. Also having a regexp selector on a given label name generally implies that such label does exist, not that it is not present at all.

**Comment by curlup** [comment]
I'm just saying that we see our clients use sometimes different sets of labels, where one set is a superset of another, and when they are asking how to select only those that do not have a particular extra label, we give them this workaround. 

In my example I used regex just to get "label `additional` is of not any value" behaviour, that's all. I think it might be reproduced with not only regex but other operators that allow a wide selection as well.
