### ISSUE TITLE
Reserved label names? __name__ comes to mind

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#52]
.

**Comment by brian-brazil** [comment]
We should reserve the __ prefix, and also recommend against common target labels such as instance, job, region, shard, cluster, team, datacenter etc. to avoid clashes.

In addition we should recommend against "type", as it's very generic.

**Comment by pimvanpelt** [comment]
Agreed on __ being reserved. Regarding common target labels: we should specify which labels we mean exactly. There's likely multiple conventions out in the wild (at least for Borgmon we have a mishmash of cluster, dc, zone).

**Comment by brian-brazil** [comment]
I don't think we can do it exactly as conventions vary, but we can capture the common ones.

**Comment by manolama** [comment]
I'd like to avoid reserving any words as they get to be implementation specific and it's a major pain in the ass to deal with as a user. See Thrift as an example.

**Comment by curlup** [comment]
As I understand __name__ in Prometheus is just reserved `name`.
Isn't it possible to do so with instance, job, region, shard, cluster etc?
Like __instance, __job, __region__ and so on, so if a vendor needs some specific things (regarding pulling or annotation or whatever) it's possible in that namespace.

**Comment by brian-brazil** [comment]
> Isn't it possible to do so with instance, job, region, shard, cluster etc?

No, as unlike metric names which are internal things like instance labels are meant to be directly used by the user.

**Comment by RichiH** [comment]
`__.*` is reserved.

**Comment by RichiH** [comment]
`:` is reserved for user use.

**Comment by curlup** [comment]
> __.* is reserved.

@RichiH what do you mean?
