### ISSUE TITLE
Define what are valid characters in metric names and labels

### ISSUE THREAD

**Issue by pimvanpelt** [OpenObservability/OpenMetrics#53]
From #28 we discussed that not all characters are valid in metric names.
We should define the exact set of characters that are allowed in metric names.

Similarly for label names.

**Comment by pimvanpelt** [comment]
From Prometheus:
Metric Names: [a-zA-Z_:][a-zA-Z0-9_:]*
Labels: [a-zA-Z_][a-zA-Z0-9_]*

Not sure we should treat instrumentation sources differently (see #28), but if we do, we can define that instrumentation sources SHOULD NOT include ':' character.

**Comment by robskillington** [comment]
Is there a reason to constrict the label values not just to UTF8?  When monitoring things that are sometimes sharded by georegions one has a valid need to support Chinese city names in metrics, etc.

**Comment by brian-brazil** [comment]
This issue is about metric names and label names. In other issues we have consensus that label values will be full UTF-8.

**Comment by robskillington** [comment]
Makes sense, I suppose those programming primarily in other languages would still find this requirement frustrating but obviously less so if it only applies to names and label names.  

I misread the second comment "Labels: <pattern>" to apply to values too.

**Comment by hbs** [comment]
Why not use percent-encoded UTF-8 representation for metric names, and label names/values? This could have the beneficial side effect of getting rid of the quotes used by Prometheus.

**Comment by jkschneider** [comment]
This is tricky. `.` is an almost expected separator to group name taxonomies in SignalFx but is destructive to indexing in Elastic. The same kind of name taxonomy is expected in Prometheus with a `_`.

**Comment by hbs** [comment]
Is the purpose of OpenMetrics to converge on an open standard or to make people adopt the Prometheus choices?

I insist the quoting mechanism in use in the Prometheus format is unwise and incoherent (the metric name being unquoted given the reduced character set it supports).

Percent encoding is only needed for encoding comma and percent if the rest is indeed in UTF-8, thus making it quite readable by humans IMHO.

**Comment by RichiH** [comment]
The purpose is to leverage the extremely wide adoption base of Prometheus into a common standard. As such, we need to take care to maintain a painless upgrade path for this installed base.

The concept of __name__ labels is a design decision by Prometheus, which is detached from OpenMetrics. OM reserves __*__ for potential future use, but there's no connection between a metric name and a label value within OM.

Introducing new encodings in the text format is outside the scope of OM; as we also define an first-class optional protobuf format, people are free to use this, instead.
