### ISSUE TITLE
Consensus: Label values are strings only; not int, not float, not bool

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#56]

**Comment by curlup** [comment]
How about histogram bounds in labels? (https://github.com/RichiH/OpenMetrics/issues/) 
Say, the upper bound label is `le="0.01"` which is string representation of a float value, and I suppose a user might want to select them on `le<1` or alike condition.

**Comment by brian-brazil** [comment]
That's a matter for the text representation, and the ingesting backends to handle. I presume/hope we'll continue to use the `le` label as we currently do.

**Comment by jkschneider** [comment]
`le` implies that histograms are always cumulative. But this is the opinion of Prometheus. Do we intend to impose that? Atlas uses normal histograms.

**Comment by brian-brazil** [comment]
Yes, this is a hard requirement. Converting between cumulative and
non-cumulative is not hard. Internally for example most Prometheus clients
use non-cumulative histograms for contention reasons.
