### ISSUE TITLE
Labels as an array?

### ISSUE THREAD

**Issue by manolama** [OpenObservability/OpenMetrics#57]
We never brought it up but our arch had a good point; some folks are moving away from the concept of tags/labels as key/value pairs since, as a user when you're looking for a metric, you may start searching by "mysql" and don't really care if it has a key of "role" or "system_type", whatever. Should we allow for the DataDog model wherein you just have an array of strings associated with a measurement? If you want a key/value pair, just include a separator.

**Comment by brian-brazil** [comment]
Coming from Prometheus, the model where's it's just a simple list for labels is a downgrade as in practice there's always an implicit key in there. Trying to extract that back out is hard, and the generic ways of doing it are basically local conventions for turning it into key-value pairs (e.g https://www.robustperception.io/extracting-full-labels-from-consul-tags/).

It's also a general principle that you always know what your label names are and what they mean. Metrics have structure, they're not something you technically should be grepping.

**Comment by manolama** [comment]
It's a general principle for a developer to know your label names and what they mean but what about the user? If you're brand new to the system, you will always start by grepping and that's a perfectly valid use case. After you learn the layout you can use the full keys and values to get to your data quicker.

And splitting tags is a pain and usually specific, but is it something we want to enforce in a spec just because most, but not all, systems follow this convention? How would DD join OpenMetrics if we didn't accommodate their use case?

**Comment by brian-brazil** [comment]
> And splitting tags is a pain and usually specific, but is it something we want to enforce in a spec just because most, but not all, systems follow this convention?

Yes, it defeats most of the usefulness and power of labels.

> How would DD join OpenMetrics if we didn't accommodate their use case?

DataDog supports key-value labels, and as it stands their agent can ingest the Prometheus text format. I don't forsee a problem there.
