### ISSUE TITLE
Target Users of the Format?

### ISSUE THREAD

**Issue by manolama** [OpenObservability/OpenMetrics#58]
This ties back into the scope. Who do we expect to be consumers of our format?

* IoT sources and destinations? (need accuracy and precision as well as geo-data)
* The science community? (needs accuracy and precision, some may need historical timestamps [negative epochs] or future timestamps)
* Financial trading systems? (probably not but?)
* or just systems and application monitoring? (can get away will low precision and accuracy for the most part)

**Comment by brian-brazil** [comment]
I expect the primary users to be systems and applications monitoring. If others find it useful that's great, but they're not the target audience.

**Comment by brian-brazil** [comment]
There's overlap, but it's the bits that don't overlap that would concern me. Particularly for scientific usage.

**Comment by RichiH** [comment]
No limit on target audience; put something about roots in pre-amble
