### ISSUE TITLE
Histograms as first-class metrics

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#6]
@beorn7 do you want to write down / link your braindump in here? We should discuss this and make a deliberate decision either way.

**Comment by beorn7** [comment]
- [Slide deck from Prometheus dev summit](https://docs.google.com/presentation/d/1WUSerlBAB6I6jz6Vo3d6VScCgMk7eOrTCOCJZIcjnyc/edit?usp=sharing).
- [Discussion on `prometheus-developers@`](https://groups.google.com/forum/#!topic/prometheus-developers/A-BCPGUSYzw).
- This has a lot of crosslinks with the [protobuf vs. text format discussion](https://github.com/RichiH/OpenMetrics/blob/master/protobuf_vs_text.md).

**Comment by manolama** [comment]
Ties in with #4 and I'd definitely like to see this along with extensibility. Storing associative histos, digests and sketches will be really important.

**Comment by brian-brazil** [comment]
This issue is about fixed bucket histograms that we have for Prometheus. If you want types beyond that, I'd suggest opening a new issue. See also #27

**Comment by manolama** [comment]
Then I'll +1 this saying that bucketed histos should be a first-class metric.

**Comment by RichiH** [comment]
Consensus: There will be a distribution point of some sorts.

**Comment by ericanthonysilva** [comment]
At the risk of being pedantic, I think we should be certain refer to this as a distribution. A histogram is the visual representation of a distribution, not the data itself.
