### ISSUE TITLE
Official TCP port

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#60]
We should get an official (default) port while we're at it.

**Comment by brian-brazil** [comment]
I'm not sure this makes sense, as what we really need is one per application/exporter - which is thousands of ports.

**Comment by RichiH** [comment]
There has to be a default. Traditional vendors will have one endpoint per device/service and they will need something default to sit on. Once again, think SNMP.

Plus, leaving this open will invite bikeshedding during the IETF phase.

**Comment by SuperQ** [comment]
Does anyone do SNMP over TCP?  We could just claim `161/tcp`. :grin:

**Comment by RichiH** [comment]
Old protocols always got both TCP and UDP; TCP/161 is reserved for SNMP.

These smell vacant, though:
````
health-polling     1161        tcp    Health Polling
health-polling     1161        udp    Health Polling
ill                1611        tcp    Inter Library Loan           [Niall_Murphy]                                        [Niall_Murphy]
ill                1611        udp    Inter Library Loan           [Niall_Murphy]                                        [Niall_Murphy]
````

**Comment by manolama** [comment]
Is it just for a listening port for receiving these messages? Do we need diff ports for different protocols? (Text vs *shrug*?)

**Comment by SuperQ** [comment]
@manolama This would be the polling port, but could also be a receiving port as well.  No need for more than one, as we already use [Content negotiation](https://en.wikipedia.org/wiki/Content_negotiation) for deciding on protocol encoding.  With text being the default.

**Comment by brian-brazil** [comment]
The only reason for more than one port may be TLS.

**Comment by manolama** [comment]
> @manolama This would be the polling port, but could also be a receiving port as well. No need for more than one, as we already use Content negotiation for deciding on protocol encoding. With text being the default.

Are we also including the protocol in this standard? Is it wise to force the overhead of HTTP?

**Comment by brian-brazil** [comment]
The format would be agnostic, however I think it'd be wise to include a recommendation to provide a HTTP endpoint.

**Comment by luca3m** [comment]
I vote also for a default port. It will make pollers configuration easier since application don't have to specify a port if they are using the default. Within the same port it will not be hard to negotiate protocol between HTTP1 and 2 or content format.

**Comment by brian-brazil** [comment]
Additional thing around HTTP: We need to select a Content-Type
