### ISSUE TITLE
Considerations about TLS

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#61]

**Comment by brian-brazil** [comment]
What did you have in mind?

**Comment by manolama** [comment]
Are we limiting this project to HTTP? What about HTTP2? Straight TCP? What about support for UDP which is common with some systems (e.g. statsd)

**Comment by RichiH** [comment]
people SHOULD use TLS unless on self-controlled networks; OM has a wider scope than Prometheus.

**Comment by RichiH** [comment]
Also see https://github.com/OpenObservability/OpenMetrics/pull/93/commits/99fa270a04c32254d38aaf65872b73bd2d899416#diff-38381f1cf184134298e205fddc53d1beR116

I am seriously considering to go along the route of "if you do it, do it right" and mandating a minimum version of TLS.

**Comment by pimvanpelt** [comment]
Please make sure to keep the optional nature of TLS (iow SHOULD and not MUST).
I'm thinking of microcontrollers and IOT which may export metrics, and do not always have the luxury of crypto.

**Comment by brian-brazil** [comment]
"Where possible" is already SHOULD

**Comment by RichiH** [comment]
Valid point; changed.
