### ISSUE TITLE
Relation to existing specs

### ISSUE THREAD

**Issue by jhermann** [OpenObservability/OpenMetrics#65]
There are at least 2 similar projects:

* http://metrics20.org/spec/
* https://github.com/b/statsd_spec

Some words on how this is similar or different and possibly a comparison matrix could be useful.

**Comment by RichiH** [comment]
Metrics 2.0 is somewhat dormant and @dieterbe prefers to wait with comments on OM until we have more text.

I will have a look at the latter.

**Comment by RichiH** [comment]
The latter is dimensionless; one of OM's major selling points are its arbitrary dimensions.

**Comment by brian-brazil** [comment]
Statsd is fundamentally about events, this spec (and Metrics 2.0) are about metrics.

**Comment by StevenLeRoux** [comment]
Here is another (old) one : https://github.com/StevenLeRoux/TimeSeries_Format_Specification
