### ISSUE TITLE
Add considerations around scrape frequency and latency

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#68]
One of the issues with SNMP is that devices support the SNMP protocol, but are so slow to respond that it is effectively useless. For example 15+ minutes to get interface stats. It's also common that pulling such data will eat all the CPU of the device.

I think we should have users expect that a scrape every few seconds is normal, that each scrape should get fresh data, and that scrapes may occur concurrently.  Standard scrapes should take say <10s, and heavier scrape of optional heavy metrics should be <1m.

We also need to figure out how to make the wording apply to push, as this is a bit easier to explain with pull.

**Comment by SuperQ** [comment]
I would suggest tightening up the timing to 1s for "normal" scrapes, 10s for "large" scrapes, and 1m for scrapes that involve polling external data sources.

**Comment by RichiH** [comment]
SHOULD 1s, 10s

**Comment by fche** [comment]
Could the scrape target provide metadata about its own preferred scraping interval / latency?  Perhaps as comment metadata, or HTTP retry-after: response headers?

**Comment by RichiH** [comment]
Do you have specific use cases in mind?

This could easily be exposed as a time series within normal OM, but I
am unsure what goals you want to achieve.

**Comment by SuperQ** [comment]
Could be useful as part of service discovery. I would think a http header would be a more appropriate place to put this kind of info.

**Comment by brian-brazil** [comment]
The point of this consideration is that vendors of some devices can't be scraped even at a 15m interval, and that we're encouraging that not to happen with openmetrics.

**Comment by RichiH** [comment]
Interesting point. We could put in considerations and it what time they
SHOULD NOT exceed.

Sent by mobile; please excuse my brevity.

**Comment by sumkincpp** [comment]
Faced with a case for some systems where you should not scrape too slow(since you can miss average/aggregated point values) or too fast(since you get stale data). For the first case it might be something with "exact" scrape interval. The second case can be properly handled only by using timestamps.

**Comment by brian-brazil** [comment]
> since you can miss average/aggregated point values

Counters don't have this issue.

> since you get stale data

I don't see how the data would be stale.

**Comment by sumkincpp** [comment]
> > since you get stale data
> 
> I don't see how the data would be stale.

The case of intermediate system which supports its's own shifting window and updates exposed values *exactly* at every scrape interval. If you scrape too fast you can get same (old) values twice or more times.

**Comment by brian-brazil** [comment]
That's fundamentally a fragile system, and we're trying to discourage calculation of metrics on the client side.
