### ISSUE TITLE
Specify support for metric aggregation?

### ISSUE THREAD

**Issue by jeromefroe** [OpenObservability/OpenMetrics#69]
I was curious if it was in the purview of OpenMetrics to specify what kinds of metric aggregation a monitoring system should support? Prometheus, through [recording rules](https://prometheus.io/docs/practices/rules/), and InfluxDB, through [continuous queries](https://docs.influxdata.com/influxdb/v1.3/query_language/continuous_queries/), both support arbitrary post-ingestion aggregation. Users can define a query that is continuously evaluated and the result of the query is stored in the monitoring system alongside the data from which the result was calculated. On the other hand, [StatsD](https://github.com/etsy/statsd/blob/master/docs/metric_types.md), and by extension [DogStatsD](https://docs.datadoghq.com/guides/dogstatsd/), both support pre-ingestion aggregation, specific metrics are aggregated together before ingestion and only the result of the aggregation is stored in the monitoring system. Given that the latter systems use the type of the metric to determine which aggregation to perform, it seems that the kinds of aggregation supported by a monitoring system are inextricably tied to the metric definitions themselves. 

I believe this issue is also related to #67 since if a monitoring system were to support aggregating summaries before ingestion, then Q-Digest is a potential way to do just that. Defining what forms of aggregation should be supported may then guide what types of metrics should be supported as well.

**Comment by brian-brazil** [comment]
Statsd&friends are based on event logging. The presumption is that that sort of thing happens before they become metrics (usually in a client library), and it's only those metrics that'd then be in scope for OpenMetrics.

> Defining what forms of aggregation should be supported may then guide what types of metrics should be supported as well.

This is what counters, summaries and histograms are.

**Comment by jeromefroe** [comment]
I see, so the metrics supported by a StatsD-style client library aren't considered in scope, only the output of a StatsD-style daemon is relevant, insofar as it produces metrics defined by the OpenMetrics standard?

**Comment by brian-brazil** [comment]
Yes, however it would be wise to have a statsd-like thingy that things like PHP could integrate with. Presently the advice with Prometheus is to use the statsd protocl with our statsd_exporter, which isn't the most elegant.

**Comment by jeromefroe** [comment]
Yea, my thought when opening the issue was that an OpenMetrics version of the [StatsD spec](https://github.com/b/statsd_spec) for aggregating metrics prior to ingestion might be beneficial. It would then be possible to say how StatsD-like event-based metrics can be aggregated into the officially supported metrics types.

**Comment by brian-brazil** [comment]
Thinking on this, I think it'd be best to have this completely separate from the OpenMetrics spec to avoid confusion. At most a brief reference in the BCP section.

We only really need one implementation of this, and the spec should be very similar to statsd but with labels. The only real change there beyond the obvious that I'd like metrics to be pre-registered on startup by clients, as that's one downside of the statsd approach that we can mitigate.

**Comment by ST-DDT** [comment]
@brian-brazil Are you referring to the metric names alone or to all metric name label combinations?

**Comment by brian-brazil** [comment]
Both preferably.

**Comment by ST-DDT** [comment]
Well, that might be a problem. I'm pretty sure that I can get the metric names at startup, but all possible label combinations might be a bit hard, as it requires a strong coupling between the components and the metric service.

Cases where not all label values can be known at startup time:
* Dynamic thread/worker count based on load with the thread/worker being encoded in the metric
* HTTP status codes in http responses (I don't want to register all codes for all endpoinds)
* Any code that would work like this: [`micrometer-TimedAspect`](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java#L78-L84)

**Comment by SuperQ** [comment]
@ST-DDT Metric registration and label values are separate issues. OpenMetrics will support creation of new label values on the fly just like Prometheus would.
