### ISSUE TITLE
Unify escaping

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#7]
Currently there's slightly different escaping rules for label values and help string. It's not unlikely that implementors will get this incorrect, so we should unify on just one approach.

https://github.com/prometheus/docs/issues/550

**Comment by mattbostock** [comment]
For convenience, from https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details:

> label_value can be any sequence of UTF-8 characters, but the backslash, the double-quote, and the line-feed characters have to be escaped as \\, \", and \n, respectively.

> HELP lines may contain any sequence of UTF-8 characters (after the metric name), but the backslash and the line-feed characters have to be escaped as \\ and \n, respectively.

Do we want double quotes to be escaped as `\"` in the HELP lines?

**Comment by brian-brazil** [comment]
That would be the simplest way to handle it.
