### ISSUE TITLE
Annotation/info metric type

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#71]
General issue to track things related to the annotation metric pattern, which looks something like
    
    python_info{implementation="CPython",major="3",minor="5",patchlevel="2",version="3.5.2"} 1.0

in the text format.

I would like to propose we start calling these "info" metrics instead, as "annotation" is too overloaded a word and we keep on getting confused.

**Comment by RichiH** [comment]
Agreed, that's what I have heard them referred to as, in the past.

Slightly related to https://github.com/RichiH/OpenMetrics/issues/4#issuecomment-316951571
