### ISSUE TITLE
Line endings MUST be \n

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#72]
We get the odd user attempting \r\n for Prometheus, we should ensure it's clear that that's not valid.

**Comment by pimvanpelt** [comment]
What an amazing coincidence? :)
https://github.com/mongoose-os-libs/prometheus-metrics/commit/1b386d49688e9f8ca872cb3776e3b08ae3eecec7

was submitted 21min ago. Why would we be strict on \r\n vs \n ?

**Comment by brian-brazil** [comment]
It's not the first time we've seen this confusion, merely the most recent.

In general with formats the fewer ways there are to do the same thing, the better.

**Comment by finkr** [comment]
For Windows users that use the `textfile` collector of wmi-exporter, they may have hard time creating a `foo.prom` file without `\r\n`.

Is it up to the exporter to convert it ?

**Comment by brian-brazil** [comment]
If someone is working in a format which is not openmetrics, it's up to them to convert to a format which is openmetrics. This is the same as it is today with the Prometheus formats.
