### ISSUE TITLE
Existing non-Prometheus consumers of Prometheus exposition format

### ISSUE THREAD

**Issue by discordianfish** [OpenObservability/OpenMetrics#73]
Hi,

I remember someone (@RichiH?) saying that the most important aspect to get a format standardized is by actually having people use it in the wild. Therefor I think it would be useful to collect a list of non-Prometheus systems collecting metrics from the Prometheus exposition format.

- https://github.com/DataDog/dd-agent: looks like they want to extend/generalize it's support: https://github.com/DataDog/dd-agent/pull/3317#issuecomment-346875945
- https://github.com/influxdata/kapacitor
- https://www.outlyer.com
- https://sensuapp.org: https://blog.sensuapp.org/the-sensu-prometheus-collector-972c441d45e

**Comment by tsg** [comment]
[Metricbeat](https://github.com/elastic/beats), from the Elastic stack, also does that: https://www.elastic.co/guide/en/beats/metricbeat/6.1/metricbeat-metricset-prometheus-collector.html

**Comment by brian-brazil** [comment]
Sysdig too: https://sysdig.com/blog/prometheus-metrics/

**Comment by brian-brazil** [comment]
https://signalfx.com/blog/metrics-from-prometheus-exporters-are-now-available-with-the-sfx-smart-agent/

**Comment by RichiH** [comment]
Spoke to them yesterday. They are determined to maintain compability and
also want to support OM.

Sent by mobile; please excuse my brevity.

**Comment by simonpasquier** [comment]
OVH supports the Prometheus format too: https://github.com/ovh/beamium

**Comment by fche** [comment]
Since 2017, performance copilot (http://pcp.io/) supports prometheus exposition format in both read and write directions: it can generate as well as consume it.
