### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#76]
As the name is gaining more traction and notwithstanding http://www.paulgraham.com/name.html , I registered three domain names. I am not truly happy with any of them, but here we are; and here they are:

* epimetrics.io (Epimetheus, unlucky brother of Proemtheus) - this is more for documentation; I blocked that ages ago
* openmetrics.tech
* openmetrics.xyz

**Comment by jeromefroe** [comment]
On a whim, I put out an offer to buy openmetrics.io from the current owners and they accepted. I set up forwarding to this Github repo for the moment but once we have a site I can update it with the corresponding IP if we want to use that domain.

**Comment by SuperQ** [comment]
Great!
