### ISSUE TITLE
Monarch-style push?

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#77]
Should we specify a mode in which the ingestor opens a connection, but the client is free to send protos any time they please?

The model has advantages in certain scenarios, but we currently don't have anything which needs that scaling.

**Comment by brian-brazil** [comment]
That's out of scope for the standard I'd say, I'd not mention transports beyond bog standard HTTP.

**Comment by RichiH** [comment]
Put BCP

**Comment by StevenLeRoux** [comment]
It would mean the format would be the same between exposition and input format.

There is a use case where exposing differs fundamentally from ingestion : batch ingest / dump

In this way, you will end up with multiple line with the same metadata, just having time/value to differ. This means a lot of useless parsing that can be avoid using a special key when a metadata is unchanged on the second line. 

Example from Warp10 : 

1525827923000000// long.series.to.be.parsed{with=labels,plenty=of-them} T
=1525827923000001// F
=1525827923000002// T
=1525827923000003// -F

This saves a lot of ressources for batch ingestion.

**Comment by brian-brazil** [comment]
We're okay with redundancy like this for the initial version, compression buys us a lot.

**Comment by StevenLeRoux** [comment]
Ok. Keep in mind that it's a just parsing optimisation, not really optimising the transport due to compression gains.
