### ISSUE TITLE
Register content-type?

### ISSUE THREAD

**Issue by RichiH** [OpenObservability/OpenMetrics#79]
Do we need to register openmetrics/text or text/openmetrics somewhere? https://github.com/RichiH/OpenMetrics/issues/8

**Comment by satterly** [comment]
It should probably be "application/openmetrics".

See https://tools.ietf.org/html/rfc2046#section-4.5

**Comment by hollodotme** [comment]
IMO `text/openmetrics` makes sense. As @SuperQ said, it's a human-readable text format/standard and nothing application specific.

Media types should be registered at iana.org. 
[Here's the list of all text media types.](https://www.iana.org/assignments/media-types/media-types.xhtml#text)

How to register a media type is [explained in this RFC](https://tools.ietf.org/html/rfc6838), where [section 4.2.1](https://tools.ietf.org/html/rfc6838#section-4.2.1) also says that a `charset` parameter must be added, if the charset is not laid out in the payload itself, like in `text/xml`. 

So `text/openmetrics; charset=utf-8` should do the job.

A registration template can be found in [section 5.6](https://tools.ietf.org/html/rfc6838#section-5.6)

**Comment by RichiH** [comment]
I am sure the rfc editors will give guidance on this once we are that far.
I don't care too much what we get as long as it makes sense.

Sent by mobile; please excuse my brevity.

>

**Comment by hollodotme** [comment]
Fair points, @satterly.
Sorry, didn't read the application section careful enough.

**Comment by SuperQ** [comment]
@satterly Thanks, `application/xml` is a great example.

What about `application/openmetrics-text`, to differentiate it from say `application/openmetrics-proto`.
