### ISSUE TITLE
Exposition format: charset in content-type

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#8]
`text/plain; version=0.0.4` should probably be extended by the charset: `text/plain; version=0.0.4; charset=utf-8`. Also, we should clarify that the charset is always UTF-8, even if the text format is used as a fallback for an incomplete or unknown content-type.

https://github.com/prometheus/docs/issues/557

**Comment by mattbostock** [comment]
How do we want to present this, as best practice if exposing the metrics over HTTP? See also: #41
