### ISSUE TITLE
MetricsFile : a way to describe metrics semantic

### ISSUE THREAD

**Issue by StevenLeRoux** [OpenObservability/OpenMetrics#80]
Hi,

I've worked with friends on a way to describe the metrics semantic. The idea is to push a MetricsFile alongside with your application code and a PaaS provider or our app scheduler, can use it to automatically grab your metrics from you app, and generate the corresponding dashboard.

Here is a sample file : https://github.com/CleverCloud/metrics-spec/blob/master/data/example.yaml

This first part only provide the semantic, not the dashboard layout.

I think this should be part of OpenMetrics to let a user know which metrics are important from a /varz endpoint and how this metrics can be used. This is useful because while aggregating metrics, an automated process couldn't guess if the first local reduction has to be a SUM or a MEAN, then a global reduction could also be both. This file helps to define the metrics applied to the business logic behind.

**Comment by brian-brazil** [comment]
This looks very monitoring-systems specific, and presumes that the person writing the instrumentation knows how their code will ultimately be used - which is rarely true and could result for example in a typical application having hundreds of "important" metrics from each of its constituent libraries defining their own metrics as important.

I think this sort of thing is best done outside the metrics format.

**Comment by StevenLeRoux** [comment]
It's not really tied to monitoring, because application metrics could be business related.

See it as the way for developer to provide a file that automate metrics stuff instead of having a documentation to describe which metrics are interesting to look for, and what is the semantic behind.

Its application domain are : 
 
 - applications (custom dev, prometheus, database, ...) 
 - clustered solutions (couchbase, kafka, hbase, ...)
 - frameworks (vertx, akka, ...)

**Comment by RichiH** [comment]
Please see the considerations around this in https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md#thresholds
