### ISSUE TITLE
Specify how to deal with UTF-8 BOMs

### ISSUE THREAD

**Issue by brian-brazil** [OpenObservability/OpenMetrics#9]
https://github.com/prometheus/docs/issues/542

**Comment by mattbostock** [comment]
@beorn7's suggestion of:

> "BOMs are not part of the protocol. Creators MUST not add BOMs but consumers MAY filter them out instead of error out."

...in line with [RFC3629](https://tools.ietf.org/html/rfc3629) seems like the right approach.

Related, we should specify the format as being utf-8: #8
