### ISSUE TITLE
transfer this repo to OpenObservability

### ISSUE THREAD

**Issue by caniszczyk** [OpenObservability/OpenMetrics#96]
Instead of forking the repo, can you please xfer this org there:

1) delete this: https://github.com/OpenObservability/OpenMetrics
2) transfer this repo: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by caniszczyk** [comment]
friendly ping @RichiH

**Comment by lucperkins** [comment]
@caniszczyk Done
